Repository hiero-ledger/solo, pull requests merged in 2024-10, with the labels that each got.

#636 fix: Direct calling of node stop and start commands
  src/commands/node.mjs
Labels: Bug

#648 ci: change to using solo-charts repo and solo-containers repo
  .github/ISSUE_TEMPLATE/feature_enhancement.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/workflows/script/relay_smoke_test.sh
  README.md
  README.md.template
  examples/custom-network-config/Taskfile.yml
  package.json
  ruleset.xml
  src/commands/account.mjs
  src/commands/cluster.mjs
  src/commands/flags.mjs
  src/commands/init.mjs
  src/commands/mirror_node.mjs
  src/commands/network.mjs
  src/commands/node.mjs
  src/commands/node/tasks.mjs
  src/commands/prompts.mjs
  src/commands/relay.mjs
  src/core/account_manager.mjs
  src/core/constants.mjs
  src/core/helpers.mjs
  src/core/profile_manager.mjs
  src/core/templates.mjs
  test/data/warmup-cluster.sh
  test/e2e/commands/account.test.mjs
  test/e2e/commands/cluster.test.mjs
  test/e2e/commands/mirror_node.test.mjs
  test/e2e/commands/network.test.mjs
  test/e2e/commands/node_delete.test.mjs
  test/e2e/commands/node_local_hedera.test.mjs
  test/e2e/commands/node_local_ptt.test.mjs
  test/e2e/commands/node_update.test.mjs
  test/e2e/commands/node_upgrade.test.mjs
  test/e2e/commands/relay.test.mjs
  test/e2e/commands/separate_node_add.test.mjs
  test/e2e/commands/separate_node_delete.test.mjs
  test/e2e/core/account_manager.test.mjs
  test/e2e/core/chart_manager.test.mjs
  test/e2e/core/k8_e2e.test.mjs
  test/e2e/core/platform_installer_e2e.test.mjs
  test/e2e/e2e_node_util.js
  test/e2e/setup-e2e.sh
  test/test_add.mjs
  test/test_util.js
  test/unit/core/helpers.test.mjs
  test/unit/core/profile_manager.test.mjs
  version.mjs
Labels: Improvement

#654 chore: Refactor node.mjs
  README.md
  package-lock.json
  package.json
  src/commands/flags.ts
  src/commands/index.ts
  src/commands/node.ts
  src/commands/node/configs.ts
  src/commands/node/flags.ts
  src/commands/node/handlers.ts
  src/commands/node/index.ts
  src/commands/node/tasks.ts
  src/commands/prompts.ts
  src/core/helpers.ts
  src/core/task.ts
  src/core/yargs_command.ts
  test/e2e/commands/network.test.ts
  test/e2e/commands/node_delete.test.ts
  test/e2e/commands/node_update.test.ts
  test/e2e/commands/node_upgrade.test.ts
  test/e2e/commands/separate_node_add.test.ts
  test/e2e/commands/separate_node_delete.test.ts
  test/e2e/e2e_node_util.ts
  test/test_add.ts
  test/test_util.ts
  test/unit/commands/node.test.ts
Labels: P2, Tech Debt
