Repository hiero-ledger/solo, pull requests merged in 2025-05, with the labels that each got.

#1714 feat: Add dependency injections to all remaining command classes
  src/business/runtime-state/local-config-runtime-state.ts
  src/commands/account.ts
  src/commands/base.ts
  src/commands/cluster/index.ts
  src/commands/cluster/tasks.ts
  src/commands/deployment.ts
  src/commands/explorer.ts
  src/commands/flags.ts
  src/commands/index.ts
  src/commands/init.ts
  src/commands/mirror-node.ts
  src/commands/network.ts
  src/commands/node/index.ts
  src/commands/relay.ts
  src/core/dependency-injection/container-init.ts
  src/core/dependency-injection/inject-tokens.ts
  src/core/dependency-injection/singleton-container.ts
  src/core/dependency-injection/value-container.ts
  src/index.ts
  test/e2e/commands/account.test.ts
  test/e2e/commands/block-node.test.ts
  test/e2e/commands/cluster.test.ts
  test/e2e/commands/dual-cluster-full.test.ts
  test/e2e/commands/network.test.ts
  test/e2e/commands/relay.test.ts
  test/e2e/integration/commands/init.test.ts
  test/helpers/command-invoker.ts
  test/test-container.ts
  test/test-utility.ts
  test/unit/commands/base.test.ts
  test/unit/commands/cluster.test.ts
  test/unit/commands/network.test.ts
  test/unit/commands/node.test.ts
Labels: PR: Needs Team Approval, PR: Ready to Merge

#1946 fix: solo should exit with non-zero code when exception is thrown
  .github/workflows/script/update_md.sh
  src/core/error-handler.ts
Labels: PR: Needs Team Approval

#1947 feat: update to latest explorer release v24.15.0
  .github/workflows/script/gcs_test.sh
  docs/site/content/User/AccessHederaServices.md
  examples/Taskfile.examples.yml
  examples/create-topic.js
  resources/hedera-explorer-values.yaml
  src/core/constants.ts
  test/e2e/commands/dual-cluster-full.test.ts
  version.ts
Labels: PR: Ready to Merge

#1950 feat: fix apple silicon issue with java 21
  resources/extract-platform.sh
  src/commands/block-node.ts
  src/commands/node/tasks.ts
  src/core/helpers.ts
  src/core/network-nodes.ts
  src/core/platform-installer.ts
  test/e2e/commands/network.test.ts
  test/e2e/integration/commands/init.test.ts
  version.ts
Labels: PR: Needs Manager Approval

#1903 chore: update documentation due to command changes
  .github/workflows/script/update_md.sh
  DEV.md
  docs/site/content/User/AccessHederaServices.md
  docs/site/content/User/DebugLog/HowToDebugHederaServicesAndPlatformSDK.md
  docs/site/content/User/DebugLog/HowToDebugHederaServicesAndPlatformSDK/jvm-hedera-app.png
  docs/site/content/User/Env.md
  docs/site/content/User/FAQ.md
  docs/site/content/User/HederaDeveloper.md
  docs/site/content/User/PlatformDeveloper.md
  docs/site/content/User/SDK.md
  docs/site/content/User/SoloCLI.md
  docs/site/content/User/SoloWithMirrorNode.md
  docs/site/content/User/StepByStepGuide.md.template
  src/core/account-manager.ts
  src/core/constants.ts
  src/core/lock/interval-lock.ts
  src/core/lock/listr-lock.ts
  test/unit/core/profile-manager.test.ts
Labels: P0, PR: Needs Manager Approval

#1961 chore: rename explorer flag
  .github/workflows/script/gcs_test.sh
  DEV.md
  Taskfile.yml
  docs/site/content/User/Env.md
  docs/site/content/User/SoloCommands.md
  docs/site/content/User/StepByStepGuide.md
  examples/Taskfile.yml
  examples/custom-network-config/Taskfile.yml
  examples/external-database-test/Taskfile.yml
  examples/network-with-domain-names/Taskfile.yaml
  examples/performance-tuning/latitude/Taskfile.yml
  examples/solo-gke-test/Taskfile.yml
  resources/hiero-explorer-values.yaml
  src/commands/explorer.ts
  src/commands/flags.ts
  src/core/config/remote/common-flags-data-wrapper.ts
  src/core/config/remote/interfaces/remote-config-common-flags-struct.ts
  src/core/config/remote/interfaces/remote-config-metadata-struct.ts
  src/core/config/remote/metadata.ts
  src/core/config/remote/remote-config-manager.ts
  src/core/config/remote/remote-config-validator.ts
  src/core/constants.ts
  src/data/schema/migration/impl/local/local-config-v1-migration.ts
  test/data/v0-35-1-remote-config.yaml
  test/e2e/commands/dual-cluster-full.test.ts
  test/e2e/integration/core/remote-config-validator.test.ts
  test/unit/core/config/remote/metadata.test.ts
  test/unit/data/schema/migration/impl/remote/remote-config-v1-migration.test.ts
  test/unit/data/schema/model/local/local-config.test.ts
  test/unit/data/schema/model/remote/remote-config.test.ts
  version.ts
Labels: PR: Needs Team Approval

#1964 feat: update upgrade e2e test
  resources/extract-platform.sh
  src/commands/flags.ts
  src/commands/node/config-interfaces/node-upgrade-config-class.ts
  src/commands/node/config-interfaces/node-upgrade-context.ts
  src/commands/node/flags.ts
  src/commands/node/handlers.ts
  src/commands/node/tasks.ts
  test/e2e/commands/node-upgrade.test.ts
  version-test.ts
Labels: PR: Needs Team Approval

#1988 chore: Update MAINTAINERS.md
  MAINTAINERS.md
Labels: Documentation

#1998 fix: resolve post install failure due to c8
  package-lock.json
  package.json
Labels: Bug

#2000 chore: test run of hugo publish to gh pages for reverting when needed
  .github/workflows/flow-hugo-publish.yaml
  docs/Taskfile.yaml
  docs/content/User/StepByStepGuide.md
  docs/content/User/StepByStepGuide.md.template
  docs/data/menu/main.yml
Labels: PR: Needs Team Approval, PR: Needs Manager Approval

#1999 feat: add multiple revisioned docs support for github pages
  .github/workflows/flow-hugo-publish.yaml
  .github/workflows/script/update_md.sh
  .gitignore
  DEV.md
  README.md
  docs/site/Taskfile.yaml
  docs/site/content/en/_index.md
  docs/site/content/en/about/index.md
  docs/site/content/en/docs/solo-commands.md
  docs/site/hugo-template.yaml
  docs/site/nginx/mime.types
  docs/site/public/index.html
Labels: PR: Needs Team Approval, PR: Needs Manager Approval
