Repository hiero-ledger/solo, pull requests merged in 2025-03, with the labels that each got.

#1569 fix: yargs command async missing
  .github/workflows/zxc-e2e-test.yaml
  solo.ts
  src/commands/account.ts
  src/commands/cluster/configs.ts
  src/commands/cluster/tasks.ts
  src/commands/deployment.ts
  src/commands/explorer.ts
  src/commands/init.ts
  src/commands/mirror_node.ts
  src/commands/network.ts
  src/commands/relay.ts
  src/core/config/local_config.ts
  src/core/config/remote/remote_config_manager.ts
  src/core/constants.ts
  src/core/dependency_injection/container_init.ts
  src/core/logging.ts
  src/core/middlewares.ts
  src/core/yargs_command.ts
  src/index.ts
  test/e2e/commands/dual_cluster_full.test.ts
  test/test_container.ts
  test/test_util.ts
  test/unit/commands/network.test.ts
Labels: PR: Needs Team Approval

#1563 ci: switch to different working directory for e2e test
  .github/workflows/script/update_md.sh
  .github/workflows/zxc-update-readme.yaml
Labels: PR: Ready to Merge

#1566 feat: add freeze and restart subcommand
  src/commands/node/configs.ts
  src/commands/node/flags.ts
  src/commands/node/handlers.ts
  src/commands/node/index.ts
  src/commands/node/tasks.ts
  src/core/config/remote/enumerations.ts
  src/core/helpers.ts
  test/e2e/commands/account.test.ts
Labels: PR: Ready to Merge

#1583 fix: token flow error
  .github/workflows/zxc-update-readme.yaml
Labels: PR: Ready to Merge

#1557 chore: Update version matrix in docs for older versions of Solo
  README.md
Labels: PR: Ready to Merge

#1564 fix: generate LocalConfig in SOLO_HOME directory
  src/core/dependency_injection/container_init.ts
  test/test_container.ts
Labels: PR: Ready to Merge

#1555 feat: update solo cluster connect to only update local config
  examples/README.md
  src/commands/cluster/config_interfaces/cluster_ref_connect_config_class.ts
  src/commands/cluster/config_interfaces/cluster_ref_default_config_class.ts
  src/commands/cluster/config_interfaces/cluster_reset_config_class.ts
  src/commands/cluster/config_interfaces/cluster_setup_config_class.ts
  src/commands/cluster/config_interfaces/select_cluster_context_context.ts
  src/commands/cluster/configs.ts
  src/commands/cluster/flags.ts
  src/commands/cluster/handlers.ts
  src/commands/cluster/index.ts
  src/commands/cluster/tasks.ts
  src/commands/flags.ts
  src/core/error_messages.ts
  src/core/middlewares.ts
  test/e2e/commands/cluster.test.ts
  test/unit/commands/cluster.test.ts
Labels: PR: Ready to Merge

#1625 fix: node add/delete helm upgrade failure
  src/commands/node/tasks.ts
  version_test.ts
Labels: PR: Ready to Merge

#1622 fix: remove v1lease usage outside of `kube` folder
  src/commands/node/handlers.ts
  src/commands/node/tasks.ts
  src/core/command_handler.ts
  src/core/errors.ts
  src/core/kube/k8_client/resources/lease/k8_client_lease.ts
  src/core/kube/k8_client/resources/lease/k8_client_leases.ts
  src/core/kube/resources/lease/lease.ts
  src/core/kube/resources/lease/leases.ts
  src/core/kube/resources/resource_type.ts
  src/core/lease/interval_lease.ts
  src/core/lease/interval_lease_renewal.ts
  src/core/lease/lease_manager.ts
  src/core/lease/lease_service.ts
  src/core/lease/listr_lease.ts
  test/e2e/integration/core/lease.test.ts
  test/e2e/integration/core/lease_renewal.test.ts
  test/e2e/integration/core/noop_lease_renewal_service.test.ts
Labels: PR: Needs Team Approval, PR: Needs Manager Approval

#1546 chore: fix warnings in ClusterCommand
  src/commands/account.ts
  src/commands/cluster/config_interfaces/cluster_ref_default_context.ts
  src/commands/cluster/config_interfaces/cluster_ref_reset_config_class.ts
  src/commands/cluster/config_interfaces/cluster_ref_reset_context.ts
  src/commands/cluster/config_interfaces/cluster_ref_setup_config_class.ts
  src/commands/cluster/config_interfaces/cluster_ref_setup_context.ts
  src/commands/cluster/config_interfaces/cluster_reset_config_class.ts
  src/commands/cluster/config_interfaces/select_cluster_context_context.ts
  src/commands/cluster/configs.ts
  src/commands/cluster/handlers.ts
  src/commands/cluster/index.ts
  src/commands/cluster/tasks.ts
  src/commands/deployment.ts
  src/core/config/remote/remote_config_manager.ts
  src/core/config_manager.ts
  src/types/aliases.ts
  test/e2e/integration/core/remote_config_validator.test.ts
  test/helpers/argv_wrapper.ts
Labels: PR: Ready to Merge, PR: Needs Manager Approval

#1633 fix: log error message in tryRenew method for better debugging
  src/core/lease/interval_lease.ts
Labels: PR: Needs Team Approval, PR: Needs Manager Approval

#1632 ci: update concurrency settings in flow-hugo-publish.yaml
  .github/workflows/flow-hugo-publish.yaml
Labels: PR: Needs Team Approval, PR: Needs Manager Approval

#1636 chore: added eslint remove unused imports plugin
  eslint.config.mjs
  package-lock.json
  package.json
  src/commands/node/tasks.ts
  test/e2e/commands/node_update.test.ts
  test/e2e/commands/separate_node_delete.test.ts
  test/e2e/commands/separate_node_update.test.ts
  test/unit/commands/cluster.test.ts
  test/unit/core/config/remote/remote_config_data_wrapper.test.ts
Labels: PR: Needs Team Approval, PR: Needs Manager Approval

#1635 fix: remove use of V1MicroTime for use outside of kube folder
  src/core/config/remote/metadata.ts
Labels: PR: Needs Team Approval, PR: Needs Manager Approval

#1637 chore: removed V1ConfigMap usage outside of kube folder
  src/core/cluster_checks.ts
  src/core/config/remote/remote_config_data_wrapper.ts
  src/core/config/remote/remote_config_manager.ts
  src/core/kube/k8_client/resources/config_map/k8_client_config_map.ts
  src/core/kube/k8_client/resources/config_map/k8_client_config_maps.ts
  src/core/kube/resources/config_map/config_map.ts
  src/core/kube/resources/config_map/config_maps.ts
Labels: PR: Needs Team Approval, PR: Needs Manager Approval

#1646 chore: replace usages of 'ListrTask' & 'ListrTaskWrapper' with 'SoloListrTask' & 'SoloListrTaskWrapper'
  src/commands/flags.ts
  src/commands/node/handlers.ts
  src/commands/node/tasks.ts
  src/commands/relay.ts
  src/core/certificate_manager.ts
  src/core/config_manager.ts
  src/core/dependency_managers/dependency_manager.ts
  src/core/key_manager.ts
  src/core/lock/listr_lock.ts
  src/types/flag_types.ts
  test/e2e/e2e_node_util.ts
Labels: PR: Ready to Merge

#1655 feat: adds migration and full schema support for the local config
  package.json
  src/business/errors/illegal-argument-error.ts
  src/data/schema/migration/api/invalid-schema-version-error.ts
  src/data/schema/migration/api/schema-base.ts
  src/data/schema/migration/api/schema-migration-error.ts
  src/data/schema/migration/api/schema-validation-error.ts
  src/data/schema/migration/impl/local/local-config-v1-migration.ts
  src/data/schema/model/common/application-versions.ts
  src/data/schema/model/common/cluster.ts
  src/data/schema/model/common/user-identity.ts
  src/data/schema/model/local/deployment.ts
  src/data/schema/model/local/local-config.ts
  test/data/v0.35.1-local-config.yaml
  test/unit/data/model/local/local-config.test.ts
Labels: PR: Ready to Merge, PR: Unresolved Comments

#1664 fix(multi-cluster): make remote config features required
  src/commands/account.ts
  src/commands/deployment.ts
  src/commands/flags.ts
  src/commands/network.ts
  src/commands/node/tasks.ts
  src/core/account-manager.ts
  src/core/config/local-config.ts
  src/core/config/remote/remote-config-manager.ts
  src/core/resolvers.ts
  test/test-util.ts
  test/unit/core/local-config.test.ts
Labels: PR: Ready to Merge

#1668 chore: update HEDERA_PLATFORM_VERSION to v0.59.5
  version.ts
Labels: PR: Needs Team Approval, PR: Needs Manager Approval

#1669 chore: extend functionality in the dual cluster full e2e test
  src/commands/deployment.ts
  src/commands/init.ts
  src/core/config/local-config.ts
  src/core/config/remote/remote-config-manager.ts
  src/core/config/remote/remote-config-validator.ts
  test/data/local-config.yaml
  test/e2e/commands/dual-cluster-full.test.ts
Labels: PR: Needs Team Approval

#1658 feat: local config cleanup maintenance
  src/commands/cluster/handlers.ts
  src/commands/deployment.ts
  src/commands/flags.ts
  src/commands/init.ts
  src/commands/network.ts
  src/core/config/local-config.ts
  src/core/middlewares.ts
  src/index.ts
  test/unit/core/local-config.test.ts
Labels: PR: Needs Manager Approval

#1677 chore: add pull request checklist and commit message documentation
  .github/pull_request_template.md
Labels: PR: Needs Team Approval, PR: Needs Manager Approval

#1674 chore: enhance dual cluster full test with consensus node validation and network deploy functionality
  test/e2e/commands/dual-cluster-full.test.ts
Labels: PR: Needs Team Approval, PR: Needs Manager Approval

#1678 ci: increase solo-chart version
  src/commands/node/handlers.ts
  version.ts
Labels: PR: Ready to Merge

#1695 ci: update workflow to use commit sha in action
  .github/workflows/flow-gcs-test.yaml
Labels: github_actions

#1683 chore(local-config): split the local-config's functionality and data
  src/commands/base.ts
  src/commands/cluster/configs.ts
  src/commands/cluster/handlers.ts
  src/commands/cluster/tasks.ts
  src/commands/deployment.ts
  src/commands/init.ts
  src/commands/network.ts
  src/commands/node/configs.ts
  src/commands/node/tasks.ts
  src/core/config/local-config.ts
  src/core/config/local/local-config-data-wrapper.ts
  src/core/config/local/local-config-data.ts
  src/core/config/local/local-config.ts
  src/core/config/remote/remote-config-manager.ts
  src/core/config/remote/remote-config-validator.ts
  src/core/dependency-injection/container-init.ts
  src/core/error-messages.ts
  src/core/middlewares.ts
  src/core/resolvers.ts
  src/index.ts
  test/e2e/commands/dual-cluster-full.test.ts
  test/e2e/integration/commands/init.test.ts
  test/e2e/integration/core/remote-config-validator.test.ts
  test/test-util.ts
  test/unit/commands/base.test.ts
  test/unit/commands/cluster.test.ts
  test/unit/commands/network.test.ts
  test/unit/core/local-config-data-wrapper.test.ts
  test/unit/core/local-config.test.ts
Labels: PR: Ready to Merge

#1704 feat(env): Add the ability to override helm chart urls though the envs
  src/core/constants.ts
Labels: PR: Ready to Merge

#1706 chore: update pull request template to move up related issues section
  .github/pull_request_template.md
Labels: PR: Needs Team Approval, PR: Needs Manager Approval

#1671 feat: Show required and optional flags and default values in help
  src/commands/account.ts
  src/commands/cluster/flags.ts
  src/commands/cluster/tasks.ts
  src/commands/deployment.ts
  src/commands/explorer.ts
  src/commands/flags.ts
  src/commands/init.ts
  src/commands/mirror-node.ts
  src/commands/network.ts
  src/commands/node/flags.ts
  src/commands/node/tasks.ts
  src/commands/relay.ts
  src/core/dependency-injection/container-init.ts
  src/core/dependency-injection/inject-tokens.ts
  src/core/error-handler.ts
  src/core/errors/silent-break.ts
  src/core/help-renderer.ts
  src/core/helpers.ts
  src/core/middlewares.ts
  src/core/yargs-command.ts
  src/index.ts
  test/helpers/command-invoker.ts
Labels: PR: Needs Team Approval

#1721 chore: update mirror node version to v0.126.0
  resources/mirror-node-values.yaml
  version.ts
Labels: PR: Needs Team Approval, PR: Needs Manager Approval

#1687 feat(multi-cluster): add the ability to specify inside which cluster to add new node with solo node add
  src/commands/node/configs.ts
  src/commands/node/flags.ts
  src/commands/node/handlers.ts
  src/commands/node/node-add-config.ts
  src/commands/node/tasks.ts
Labels: PR: Needs Manager Approval

#1727 fix: array size of adminKey when the flag is not set
  src/commands/flags.ts
  src/commands/node/tasks.ts
  src/core/genesis-network-models/genesis-network-data-constructor.ts
Labels: PR: Ready to Merge

#1673 feat(cli): need to allow the user to pass in the domain name for mirror node, explorer, relay, and node service endpoints
  Taskfile.helper.yml
  Taskfile.yml
  examples/network-with-domain-names/Taskfile.yaml
  examples/sdk-network-connection/solo-network-connection.js
  src/commands/account.ts
  src/commands/explorer.ts
  src/commands/flags.ts
  src/commands/mirror-node.ts
  src/commands/network.ts
  src/commands/node/configs.ts
  src/commands/node/flags.ts
  src/commands/node/handlers.ts
  src/commands/node/node-add-config.ts
  src/commands/node/tasks.ts
  src/commands/relay.ts
  src/core/account-manager.ts
  src/core/genesis-network-models/genesis-network-data-constructor.ts
  src/core/profile-manager.ts
  src/core/templates.ts
  test/e2e/commands/dual-cluster-full.test.ts
  test/e2e/commands/mirror-node.test.ts
  test/e2e/commands/relay.test.ts
  test/unit/core/profile-manager.test.ts
Labels: PR: Ready to Merge

#1735 fix: create topic test
  examples/create-topic.js
Labels: PR: Needs Manager Approval

#1713 chore(types): improve the 'solo node' commands types
  src/commands/base.ts
  src/commands/node/config-interfaces/node-add-config-class.ts
  src/commands/node/config-interfaces/node-add-context.ts
  src/commands/node/config-interfaces/node-common-config-class.ts
  src/commands/node/config-interfaces/node-delete-config-class.ts
  src/commands/node/config-interfaces/node-delete-context.ts
  src/commands/node/config-interfaces/node-download-generated-files-config-class.ts
  src/commands/node/config-interfaces/node-download-generated-files-context.ts
  src/commands/node/config-interfaces/node-freeze-config-class.ts
  src/commands/node/config-interfaces/node-freeze-context.ts
  src/commands/node/config-interfaces/node-keys-config-class.ts
  src/commands/node/config-interfaces/node-keys-context.ts
  src/commands/node/config-interfaces/node-logs-config-class.ts
  src/commands/node/config-interfaces/node-logs-context.ts
  src/commands/node/config-interfaces/node-prepare-upgrade-config-class.ts
  src/commands/node/config-interfaces/node-prepare-upgrade-context.ts
  src/commands/node/config-interfaces/node-refresh-config-class.ts
  src/commands/node/config-interfaces/node-refresh-context.ts
  src/commands/node/config-interfaces/node-restart-config-class.ts
  src/commands/node/config-interfaces/node-restart-context.ts
  src/commands/node/config-interfaces/node-setup-config-class.ts
  src/commands/node/config-interfaces/node-setup-context.ts
  src/commands/node/config-interfaces/node-start-config-class.ts
  src/commands/node/config-interfaces/node-start-context.ts
  src/commands/node/config-interfaces/node-states-config-class.ts
  src/commands/node/config-interfaces/node-states-context.ts
  src/commands/node/config-interfaces/node-stop-config-class.ts
  src/commands/node/config-interfaces/node-stop-context.ts
  src/commands/node/config-interfaces/node-update-config-class.ts
  src/commands/node/config-interfaces/node-update-context.ts
  src/commands/node/config-interfaces/node-upgrade-config-class.ts
  src/commands/node/config-interfaces/node-upgrade-context.ts
  src/commands/node/configs.ts
  src/commands/node/handlers.ts
  src/commands/node/helper.ts
  src/commands/node/index.ts
  src/commands/node/tasks.ts
  src/core/account-manager.ts
  src/core/command-handler.ts
  src/core/genesis-network-models/genesis-network-data-constructor.ts
  src/core/helpers.ts
  src/core/node-overrides-model.ts
  src/core/task.ts
  src/types/index.ts
  src/types/mappings/node-service-mapping.ts
  test/e2e/commands/node-update.test.ts
  test/e2e/commands/separate-node-add.test.ts
  test/e2e/commands/separate-node-update.test.ts
  test/e2e/e2e-node-util.ts
  test/test-add.ts
  test/test-util.ts
Labels: PR: Needs Manager Approval

#1732 fix: doc start link
  .github/workflows/zxc-update-readme.yaml
  README.md
Labels: PR: Ready to Merge

#1740 refactor: update ESLint configuration to enforce explicit return types and typedef rules
  eslint.config.mjs
Labels: PR: Needs Team Approval, PR: Needs Manager Approval

#1742 test: increase timeout for dual-cluster full test and enable `solo node start` test
  test/e2e/commands/dual-cluster-full.test.ts
Labels: PR: Needs Team Approval, PR: Needs Manager Approval

#1743 fix: corrected the cluster that was being saved to mirror node component in remote config, extended dual-cluster-full-test to test mirror node deploy
  src/commands/explorer.ts
  src/commands/mirror-node.ts
  test/e2e/commands/dual-cluster-full.test.ts
  test/e2e/integration/core/account-manager.test.ts
  test/e2e/integration/core/helm/helm-client.test.ts
Labels: PR: Needs Team Approval, PR: Needs Manager Approval

#1746 chore: add eslint rule to enforce lowercase kabab `*.ts` file names and added unicorn recommended eslint rules as warnings
  docs/site/Taskfile.yaml
  eslint.config.mjs
  lint-formatter.ts
  package-lock.json
  package.json
  tsconfig.json
Labels: PR: Needs Manager Approval

#1751 chore: fixed some eslint warnings
  eslint.config.mjs
  src/commands/flags.ts
  src/commands/node/tasks.ts
  src/core/config/remote/remote-config-manager.ts
  src/core/profile-manager.ts
  src/data/key/lexer/lexer.ts
  src/data/package.ts
  src/integration/helm/impl/default-helm-client.ts
  src/integration/kube/k8-client/resources/container/k8-client-container.ts
Labels: PR: Needs Team Approval, PR: Needs Manager Approval

#1752 refactor: remove eslint warnings for rules: `unicorn/prefer-at`, `unicorn/no-useless-spread`, `unicorn/prefer-structured-clone`
  eslint.config.mjs
  package-lock.json
  package.json
  src/commands/account.ts
  src/commands/flags.ts
  src/core/config/local/local-config-data-wrapper.ts
  src/core/config/remote/remote-config-manager.ts
  src/core/helpers.ts
  src/core/key-manager.ts
  src/data/schema/migration/api/schema-base.ts
  src/data/schema/migration/impl/local/local-config-v1-migration.ts
  src/index.ts
  src/integration/kube/errors/kube-api-error.ts
  src/integration/kube/k8-client/resources/container/k8-client-container.ts
  test/helpers/argv-wrapper.ts
Labels: PR: Needs Team Approval, PR: Needs Manager Approval
