Repository hiero-ledger/solo, pull requests merged in 2025-01, with the labels that each got.

#1026 feat: add support for genesis throttle configuration
  .github/workflows/zxc-e2e-test.yaml
  Taskfile.helper.yml
  Taskfile.yml
  examples/Taskfile.examples.yml
  examples/custom-network-config/Taskfile.yml
  examples/performance-tuning/latitude/Taskfile.yml
  examples/performance-tuning/latitude/application.properties
  examples/performance-tuning/latitude/init-containers-values.yaml
  examples/performance-tuning/latitude/log4j2.xml
  examples/performance-tuning/latitude/nlg-values.yaml
  examples/performance-tuning/latitude/settings.txt
  examples/performance-tuning/solo-perf-test/Taskfile.yml
  examples/solo-gke-test/Taskfile.yml
  examples/solo-gke-test/application.properties
  examples/solo-gke-test/throttles.json
  src/commands/flags.ts
  src/commands/network.ts
  src/core/certificate_manager.ts
  src/core/helpers.ts
  test/test_util.ts
  version.ts
Labels: New Feature, P0

#1172 chore: Temporarily disable block streams
  examples/custom-network-config/application.properties
  examples/performance-tuning/solo-gke/application.properties
  examples/solo-gke-test/application.properties
  resources/templates/application.properties
Labels: PR: Needs Approval

#1154 chore: account init before relay deployment
  .github/workflows/flow-task-test.yaml
  .github/workflows/script/helper.sh
  .github/workflows/script/solo_smoke_test.sh
  docs/content/User/StepByStepGuide.md
  examples/address-book/README.md
  src/commands/flags.ts
  src/commands/mirror_node.ts
  src/commands/relay.ts
Labels: PR: Ready to Merge

#1142 feat: `solo deployment create` should use the context and cluster provided for where to save the remote config
  src/commands/cluster/configs.ts
  src/commands/cluster/handlers.ts
  src/commands/cluster/tasks.ts
  src/commands/deployment.ts
  src/core/config/local_config.ts
  src/core/k8.ts
  test/unit/commands/cluster.test.ts
Labels: PR: Ready to Merge

#1176 feat: Update solo to load remote config near entry point
  src/commands/mirror_node.ts
  src/commands/network.ts
  src/commands/node/handlers.ts
  src/commands/relay.ts
  src/core/config/remote/remote_config_manager.ts
  src/index.ts
Labels: PR: Ready to Merge

#1188 fix: update hedera explorer chart version and location
  .github/workflows/script/solo_smoke_test.sh
  Taskfile.helper.yml
  src/commands/mirror_node.ts
  src/core/constants.ts
  test/e2e/commands/mirror_node.test.ts
  version.ts
Labels: PR: Ready to Merge, PR: Checks Failed

#1182 fix: remove k8.getKubeConfig
  src/commands/cluster/tasks.ts
  src/core/config/local_config.ts
  src/core/config/remote/remote_config_manager.ts
  src/core/k8.ts
  src/index.ts
  test/unit/commands/cluster.test.ts
Labels: PR: Ready to Merge

#1177 feat: separate explorer from mirror node install/uninstall
  .github/workflows/flow-task-test.yaml
  Taskfile.helper.yml
  src/commands/explorer.ts
  src/commands/flags.ts
  src/commands/index.ts
  src/commands/mirror_node.ts
  src/core/constants.ts
  src/core/k8.ts
  test/e2e/commands/mirror_node.test.ts
Labels: PR: Ready to Merge

#1185 fix: Refactor RemoteConfigTasks class
  src/commands/cluster/handlers.ts
  src/commands/cluster/tasks.ts
  src/commands/deployment.ts
  src/commands/mirror_node.ts
  src/commands/network.ts
  src/commands/node/handlers.ts
  src/commands/relay.ts
  src/core/config/remote/listr_config_tasks.ts
  src/core/config/remote/remote_config_manager.ts
  src/core/config/remote/remote_config_tasks.ts
Labels: PR: Ready to Merge

#1156 feat(cli): reduce redundancy on context to cluster flags in command `deployment create`
  src/commands/base.ts
  src/commands/cluster/tasks.ts
  src/commands/deployment.ts
  src/commands/flags.ts
  src/commands/mirror_node.ts
  src/commands/network.ts
  src/core/config/local_config.ts
  src/core/config/remote/listr_config_tasks.ts
  src/core/config/remote/remote_config_manager.ts
  src/core/templates.ts
  src/types/config_types.ts
Labels: PR: Needs Approval

#1191 feat(remote-config): save reusable solo flags in remoteconfig
  package-lock.json
  package.json
  src/commands/deployment.ts
  src/commands/mirror_node.ts
  src/core/config/remote/common_flags_data_wrapper.ts
  src/core/config/remote/components_data_wrapper.ts
  src/core/config/remote/listr_config_tasks.ts
  src/core/config/remote/metadata.ts
  src/core/config/remote/remote_config_data.ts
  src/core/config/remote/remote_config_data_wrapper.ts
  src/core/config/remote/remote_config_manager.ts
  src/core/config/remote/types.ts
  src/index.ts
  test/unit/core/remote_config/remote_config_data_wrapper.test.ts
Labels: PR: Ready to Merge

#1208 feat(remote-config): instead of keeping just the command and the subcommand inside the remote config keep the flags as passed
  Taskfile.helper.yml
  docs/content/User/SoloCLI.md
  src/commands/flags.ts
  src/core/config/remote/remote_config_manager.ts
  src/core/config/remote/remote_config_validator.ts
  src/core/constants.ts
  src/core/helpers.ts
  src/index.ts
  src/types/flag_types.ts
  test/unit/core/helpers.test.ts
Labels: PR: Ready to Merge

#1204 feat: update solo to support pathPrefix of mirror node importer
  .github/workflows/flow-gcs-test.yaml
  .github/workflows/script/gcs_test.sh
  docs/content/User/AccessHederaServices.md
  docs/content/User/SoloWithMirrorNode.md
  src/commands/flags.ts
  src/commands/mirror_node.ts
  src/commands/network.ts
  version.ts
Labels: PR: Ready to Merge

#1219 chore(lint): manually fixed imports to be consisent
  src/commands/account.ts
  src/commands/base.ts
  src/commands/cluster/configs.ts
  src/commands/cluster/handlers.ts
  src/commands/cluster/index.ts
  src/commands/cluster/tasks.ts
  src/commands/explorer.ts
  src/commands/flags.ts
  src/commands/index.ts
  src/commands/mirror_node.ts
  src/commands/network.ts
  src/commands/node/configs.ts
  src/commands/node/handlers.ts
  src/commands/node/helper.ts
  src/commands/node/index.ts
  src/commands/node/node_add_config.ts
  src/commands/node/tasks.ts
  src/commands/relay.ts
  src/core/account_manager.ts
  src/core/config/local_config.ts
  src/core/config/remote/remote_config_data.ts
  src/core/config/remote/remote_config_data_wrapper.ts
  src/core/config_manager.ts
  src/core/dependency_managers/dependency_manager.ts
  src/core/k8.ts
  src/core/key_manager.ts
  src/core/lease/interval_lease.ts
  src/core/lease/interval_lease_renewal.ts
  src/core/lease/lease.ts
  src/core/lease/listr_lease.ts
  src/core/logging.ts
  src/core/platform_installer.ts
  src/core/process_output.ts
  src/core/task.ts
  src/core/templates.ts
  src/core/yargs_command.ts
  src/index.ts
  src/types/aliases.ts
  src/types/flag_types.ts
  src/types/index.ts
Labels: PR: Ready to Merge

#1193 feat: Add adminKey flag to node setup command
  src/commands/flags.ts
  src/commands/node/configs.ts
  src/commands/node/flags.ts
  src/commands/node/tasks.ts
  src/core/genesis_network_models/genesis_network_data_constructor.ts
  test/test_util.ts
Labels: PR: Ready to Merge

#1234 refactor: minor refactors to K8 setting private and public modifiers
  src/commands/cluster/tasks.ts
  src/core/config/local_config.ts
  src/core/k8.ts
  src/core/kube/t_directory_data.ts
  src/index.ts
  test/e2e/e2e_node_util.ts
  test/e2e/integration/core/k8_e2e.test.ts
  test/unit/commands/cluster.test.ts
Labels: PR: Needs Approval

#1235 fix: fixed merge issue with incorrect license header
  src/core/kube/t_directory_data.ts
Labels: PR: Needs Approval

#1238 refactor: create interface for K8 and composition interfaces for it, made k8.waitForPodConditions private
  src/core/k8.ts
  src/core/kube/clusters.ts
  src/core/kube/config_maps.ts
  src/core/kube/contexts.ts
  src/core/kube/leases.ts
  src/core/kube/namespaces.ts
  src/core/kube/pod.ts
  src/core/kube/pods.ts
  src/core/kube/pvcs.ts
  src/core/kube/secrets.ts
  src/core/kube/services.ts
  src/core/kube/tk8.ts
  test/e2e/integration/core/k8_e2e.test.ts
  test/unit/core/k8.test.ts
Labels: PR: Needs Approval

#1239 refactor: switch codebase to use K8 interface, added k8.listSvcs(), removed k8.kubeClient references, updated interface optional parameters
  src/commands/base.ts
  src/commands/cluster/tasks.ts
  src/commands/node/handlers.ts
  src/commands/node/tasks.ts
  src/core/account_manager.ts
  src/core/certificate_manager.ts
  src/core/config/local_config.ts
  src/core/config/remote/remote_config_manager.ts
  src/core/config/remote/remote_config_validator.ts
  src/core/container_init.ts
  src/core/kube/clusters.ts
  src/core/kube/config_maps.ts
  src/core/kube/contexts.ts
  src/core/kube/k8.ts
  src/core/kube/k8_client.ts
  src/core/kube/leases.ts
  src/core/kube/pod.ts
  src/core/kube/pods.ts
  src/core/kube/pvcs.ts
  src/core/kube/secrets.ts
  src/core/kube/services.ts
  src/core/kube/t_directory_data.ts
  src/core/lease/interval_lease.ts
  src/core/lease/lease.ts
  src/core/lease/lease_manager.ts
  src/core/platform_installer.ts
  src/index.ts
  src/types/command_types.ts
  test/e2e/commands/account.test.ts
  test/e2e/commands/node_local_hedera.test.ts
  test/e2e/commands/node_local_ptt.test.ts
  test/e2e/e2e_node_util.ts
  test/e2e/integration/commands/init.test.ts
  test/e2e/integration/core/account_manager.test.ts
  test/e2e/integration/core/k8_e2e.test.ts
  test/e2e/integration/core/lease.test.ts
  test/e2e/integration/core/lease_renewal.test.ts
  test/e2e/integration/core/platform_installer_e2e.test.ts
  test/e2e/integration/core/remote_config_manager.test.ts
  test/e2e/integration/core/remote_config_validator.test.ts
  test/test_util.ts
  test/unit/commands/base.test.ts
  test/unit/commands/cluster.test.ts
  test/unit/commands/network.test.ts
  test/unit/core/certificate_manager.test.ts
  test/unit/core/k8.test.ts
Labels: PR: Needs Approval
