Repository hiero-ledger/solo, pull requests merged in 2025-09, with the labels that each got.

#2541 docs: update versions table
  README.md
  docs/legacy-versions.md
  docs/site/Taskfile.mutate.yaml
  docs/site/hugo-template.yaml
Labels: PR: Needs Team Approval

#2484 feat: update grpcWebProxyEndpoint on node add
  src/commands/node/config-interfaces/node-add-config-class.ts
  src/commands/node/config-interfaces/node-start-config-class.ts
  src/commands/node/configs.ts
  src/commands/node/handlers.ts
  src/commands/node/tasks.ts
  src/core/helpers.ts
Labels: PR: Needs Team Approval

#2539 feat: create workflow for current examples
  .github/workflows/flow-examples-test.yaml
  .github/workflows/script/launch_network.sh
  .github/workflows/script/solo_smoke_test.sh
  .github/workflows/support/examples-test-matrix.json
  examples/address-book/README.md
  examples/address-book/Taskfile.yml
  examples/custom-network-config/Taskfile.yml
  examples/custom-network-config/application.properties
  examples/custom-network-config/init-containers-values.yaml
  examples/external-database-test/Taskfile.yml
  examples/network-with-block-node/Taskfile.yml
  examples/network-with-domain-names/Taskfile.yml
  examples/node-create-transaction/Taskfile.yml
  examples/node-delete-transaction/Taskfile.yml
  examples/node-delete-transaction/solo-node-delete-transaction.js
  examples/node-update-transaction/Taskfile.yml
  src/commands/command-definitions/consensus-command-definition.ts
  src/commands/explorer.ts
  src/commands/mirror-node.ts
  src/commands/node/tasks.ts
  src/commands/relay.ts
  src/core/config/remote/components-data-wrapper.ts
Labels: PR: Needs Manager Approval

#2570 feat: add debug logic
  .github/workflows/script/gcs_test.sh
  src/commands/command-definitions/consensus-command-definition.ts
  src/integration/helm/execution/helm-execution.ts
Labels: PR: Needs Team Approval, PR: Needs Manager Approval

#2562 fix: remove hardcoded pinger tps
  resources/mirror-node-values.yaml
  src/commands/mirror-node.ts
Labels: PR: Needs Team Approval, PR: Needs Manager Approval

#2564 fix: save component version with deploy command
  scripts/Taskfile.scripts.yml
  src/business/runtime-state/api/remote-config-runtime-state-api.ts
  src/business/runtime-state/config/remote/remote-config-runtime-state.ts
  src/commands/block-node.ts
  src/commands/explorer.ts
  src/commands/mirror-node.ts
  src/commands/network.ts
  src/commands/node/configs.ts
  src/commands/node/tasks.ts
  src/commands/relay.ts
  src/integration/helm/execution/helm-execution.ts
  test/e2e/commands/block-node.test.ts
  test/unit/commands/network.test.ts
Labels: PR: Needs Manager Approval

#2583 fix: do not run examples on pull request
  .github/workflows/flow-examples-test.yaml
Labels: PR: Needs Manager Approval

#2364 fix: bump CN to v0.64.2 to match MAINNET
  .github/workflows/script/launch_network.sh
  version-test.ts
  version.ts
Labels: PR: Needs Team Approval, PR: Needs Manager Approval

#2571 feat(test): consolidate Node Local Hedera into Node Add Local
  .github/workflows/support/e2e-test-matrix.json
  Taskfile.tests.yml
  test/e2e/commands/node-add-local.test.ts
  test/e2e/commands/node-local-hedera.test.ts
  test/test-add.ts
Labels: PR: Ready to Merge, PR: Needs Manager Approval

#2592 feat: add PodmanDependencyManager
  src/commands/init/init.ts
  src/core/chart-manager.ts
  src/core/constants.ts
  src/core/dependency-injection/container-init.ts
  src/core/dependency-injection/inject-tokens.ts
  src/core/dependency-managers/base-dependency-manager.ts
  src/core/dependency-managers/dependency-manager.ts
  src/core/dependency-managers/helm-dependency-manager.ts
  src/core/dependency-managers/index.ts
  src/core/dependency-managers/kind-dependency-manager.ts
  src/core/dependency-managers/kubectl-dependency-manager.ts
  src/core/dependency-managers/podman-dependency-manager.ts
  src/core/middlewares.ts
  src/core/package-downloader.ts
  src/core/templates.ts
  src/integration/kind/impl/default-kind-client-builder.ts
  src/integration/kind/model/create-cluster/cluster-create-response.ts
  src/integration/kube/errors/missing-active-cluster-error.ts
  src/integration/kube/errors/missing-active-context-error.ts
  src/integration/kube/k8-client/k8-client.ts
  test/e2e/integration/commands/init.test.ts
  test/e2e/integration/core/dependency-managers/kind-dependency-manager.test.ts
  test/e2e/integration/core/dependency-managers/kubectl-dependency-manager.test.ts
  test/e2e/integration/core/dependency-managers/podman-dependency-manager.test.ts
  version.ts
Labels: PR: Needs Team Approval

#2655 fix: Cherry pick gradle and mirror node fixes
  .github/workflows/flow-pull-request-checks.yaml
  .github/workflows/script/launch_network.sh
  .github/workflows/zxc-e2e-test.yaml
  docs/site/content/en/docs/env.md
  docs/site/update_md.sh
  examples/address-book/README.md
  examples/custom-network-config/README.md
  examples/external-database-test/README.md
  examples/network-with-block-node/README.md
  examples/network-with-block-node/Taskfile.yml
  examples/network-with-domain-names/README.md
  examples/node-create-transaction/README.md
  examples/node-create-transaction/Taskfile.yml
  examples/node-delete-transaction/README.md
  examples/node-delete-transaction/Taskfile.yml
  examples/node-update-transaction/README.md
  examples/node-update-transaction/Taskfile.yml
  examples/running-solo-inside-cluster/README.md
  version-test.ts
  version.ts
Labels: PR: Needs Team Approval, PR: Needs Manager Approval

#2647 chore(deps): update dependabot configuration to group dependencies and limit open pull requests
  .github/dependabot.yml
Labels: PR: Needs Team Approval, PR: Needs Manager Approval

#2624 feat: update quickstart, allow ingress controller to support regex path
  resources/ingress-controller-values.yaml
  src/commands/mirror-node.ts
  src/commands/one-shot/default-one-shot.ts
  src/core/constants.ts
Labels: PR: Needs Team Approval

#2656 feat: remove cluster setup chart
  docs/site/content/en/docs/env.md
  resources/templates/pod-monitor-role.yaml
  src/commands/cluster/config-interfaces/cluster-reference-reset-config-class.ts
  src/commands/cluster/config-interfaces/cluster-reference-reset-context.ts
  src/commands/cluster/config-interfaces/cluster-reference-setup-config-class.ts
  src/commands/cluster/config-interfaces/cluster-reference-setup-context.ts
  src/commands/cluster/configs.ts
  src/commands/cluster/flags.ts
  src/commands/cluster/handlers.ts
  src/commands/cluster/tasks.ts
  src/commands/flags.ts
  src/commands/network.ts
  src/core/cluster-checks.ts
  src/core/constants.ts
  src/integration/kube/k8-client/k8-client.ts
  src/integration/kube/k8.ts
  test/e2e/commands/cluster.test.ts
  test/e2e/integration/core/chart-manager.test.ts
  test/test-utility.ts
  test/unit/commands/cluster.test.ts
  test/unit/commands/network.test.ts
  version.ts
Labels: PR: Needs Team Approval

#2661 feat: add example to upgrade all component
  .github/workflows/support/examples-test-matrix.json
  examples/version-upgrade-test/README.md
  examples/version-upgrade-test/Taskfile.yml
  src/commands/block-node.ts
  src/commands/relay.ts
Labels: PR: Needs Team Approval

#2678 chore(test): consolidate node PEM Kill and Stop tests into dual-cluster-full
  .github/workflows/support/e2e-test-matrix.json
  Taskfile.tests.yml
  src/commands/node/config-interfaces/node-add-config-class.ts
  src/commands/node/config-interfaces/node-common-config-class.ts
  src/commands/node/config-interfaces/node-destroy-config-class.ts
  src/commands/node/config-interfaces/node-refresh-config-class.ts
  src/commands/node/config-interfaces/node-update-config-class.ts
  src/commands/node/handlers.ts
  src/commands/node/tasks.ts
  test/e2e/commands/dual-cluster-full.test.ts
  test/e2e/commands/node-pem-kill.test.ts
  test/e2e/commands/node-pem-stop.test.ts
  test/e2e/commands/tests/node-test.ts
  test/e2e/end-to-end-node-utility.ts
Labels: PR: Needs Team Approval, PR: Needs Manager Approval
