Repository hiero-ledger/solo, pull requests merged in 2025-07, with the labels that each got.

#2256 docs: update step-by-step-guide.template.md
  docs/site/content/en/templates/step-by-step-guide.template.md
Labels: PR: Unresolved Comments

#2187 feat: add new method and logic for setting the grpcProxyEndpoint()
  resources/templates/application.properties
  src/commands/node/handlers.ts
  src/commands/node/tasks.ts
Labels: PR: Needs Team Approval, PR: Needs Manager Approval

#2249 feat: add KindDependencyManager
  src/commands/init/init.ts
  src/core/constants.ts
  src/core/dependency-injection/container-init.ts
  src/core/dependency-injection/inject-tokens.ts
  src/core/dependency-managers/dependency-manager.ts
  src/core/dependency-managers/index.ts
  src/core/dependency-managers/kind-dependency-manager.ts
  src/core/package-downloader.ts
  src/core/templates.ts
  test/e2e/integration/core/dependency-managers/helm-dependency-manager.test.ts
  test/e2e/integration/core/dependency-managers/kind-dependency-manager.test.ts
  test/e2e/integration/core/remote-config-validator.test.ts
  version.ts
Labels: PR: Needs Team Approval

#2243 chore: improve .npmignore
  .npmignore
Labels: PR: Ready to Merge

#2280 feat: add port forward detach capabilities and logging at end of `solo quick-start single deploy`
  .github/workflows/script/gcs_test.sh
  .github/workflows/script/launch_network.sh
  .github/workflows/script/mirror-ingress-controller-values.yaml
  docs/site/content/en/docs/execution-developer.md
  docs/site/content/en/docs/solo-with-mirror-node.md
  docs/site/content/en/templates/step-by-step-guide.template.md
  docs/site/update_md.sh
  examples/Taskfile.examples.yml
  solo.ts
  src/business/runtime-state/api/remote-config-runtime-state-api.ts
  src/business/runtime-state/config/remote/remote-config-runtime-state.ts
  src/commands/cluster/tasks.ts
  src/commands/explorer.ts
  src/commands/flags.ts
  src/commands/mirror-node.ts
  src/commands/node/config-interfaces/node-start-config-class.ts
  src/commands/node/flags.ts
  src/commands/node/handlers.ts
  src/commands/node/tasks.ts
  src/commands/quick-start/default-quick-start.ts
  src/commands/relay.ts
  src/core/config-manager.ts
  src/core/constants.ts
  src/core/helpers.ts
  src/core/lock/interval-lock-renewal.ts
  src/core/logging/solo-logger.ts
  src/core/logging/solo-winston-logger.ts
  src/core/shell-runner.ts
  src/core/task-list/default-task-list.ts
  src/integration/kube/k8-client/resources/pod/k8-client-pod.ts
  src/integration/kube/resources/pod/pod.ts
  version.ts
Labels: PR: Needs Team Approval, PR: Needs Manager Approval

#2277 feat: enable relay websocket subchart
  .github/workflows/script/launch_network.sh
  src/commands/relay.ts
  src/core/config/remote/remote-config-validator.ts
  src/core/constants.ts
  src/data/schema/migration/impl/remote/remote-config-v1-migration.ts
  test/e2e/integration/core/remote-config-validator.test.ts
  test/unit/data/schema/migration/impl/remote/remote-config-v1-migration.test.ts
Labels: PR: Ready to Merge

#2306 fix: explorer deploy use incorrect env variable in task file
  .github/workflows/script/solo_smoke_test.sh
  examples/Taskfile.examples.yml
  examples/Taskfile.yml
Labels: PR: Ready to Merge

#2307 chore: update node logs documentation
  docs/site/content/en/docs/jvm-debugger.md
  docs/site/content/en/docs/solo-with-mirror-node.md
  docs/site/content/en/templates/step-by-step-guide.template.md
Labels: PR: Ready to Merge

#2312 chore: refactor external database to e2e test
  .github/workflows/script/helper.sh
  .github/workflows/script/solo_smoke_test.sh
  .github/workflows/support/e2e-test-matrix.json
  .github/workflows/zxc-e2e-test.yaml
  Taskfile.tests.yml
  docs/site/content/en/docs/env.md
  examples/create-topic.js
  src/commands/mirror-node.ts
  src/core/constants.ts
  test/e2e/commands/external-database.test.ts
  test/e2e/commands/tests/explorer-test.ts
  test/e2e/commands/tests/mirror-node-test.ts
  test/e2e/commands/tests/node-test.ts
  test/e2e/commands/tests/relay-test.ts
Labels: PR: Needs Team Approval, PR: Needs Manager Approval

#2313 feat: manual kick off e2e test
  .github/workflows/zxc-e2e-test.yaml
Labels: PR: Ready to Merge

#2272 fix: update Hedera platform version to v0.62.10
  .github/workflows/flow-migration-test.yaml
  .github/workflows/script/helper.sh
  .github/workflows/script/launch_network.sh
  .github/workflows/script/solo_smoke_test.sh
  .github/workflows/zxc-e2e-test.yaml
  resources/templates/application.properties
  test/e2e/commands/external-database.test.ts
  test/e2e/commands/tests/mirror-node-test.ts
  version-test.ts
  version.ts
Labels: PR: Needs Team Approval, PR: Needs Manager Approval

#2321 chore: remove unnecessary logging of argv in command handlers
  src/commands/account.ts
  src/commands/deployment.ts
  src/commands/explorer.ts
  src/commands/mirror-node.ts
  src/commands/network.ts
  src/commands/relay.ts
  src/core/yargs-command.ts
Labels: PR: Needs Team Approval, PR: Needs Manager Approval

#2344 chore: add test of envoy proxy endpoint
  test/e2e/commands/account.test.ts
Labels: PR: Needs Manager Approval

#2314 fix: add version string checking
  src/business/utils/version.ts
  src/commands/block-node.ts
  src/commands/cluster/tasks.ts
  src/commands/explorer.ts
  src/commands/mirror-node.ts
  src/commands/network.ts
  src/commands/node/configs.ts
  src/commands/node/tasks.ts
  src/commands/relay.ts
  test/e2e/commands/cluster.test.ts
  version.ts
Labels: PR: Ready to Merge

#2308 feat: helm dependency manager prefers global installation
  src/core/dependency-managers/helm-dependency-manager.ts
  test/e2e/integration/core/dependency-managers/helm-dependency-manager.test.ts
Labels: PR: Ready to Merge

#2356 feat: add flag to private key
  src/commands/account.ts
Labels: PR: Needs Manager Approval

#2322 fix: bump CN to v0.63.9, MN to v0.134, Relay to v0.69.3, BN to v0.14.0, Solo chart to v0.54.5
  .github/workflows/flow-migration-test.yaml
  .github/workflows/flow-pull-request-checks.yaml
  .github/workflows/script/launch_network.sh
  docs/site/update_md.sh
  src/commands/mirror-node.ts
  src/integration/kube/k8-client/resources/pod/k8-client-pod.ts
  version-test.ts
  version.ts
Labels: PR: Needs Team Approval, PR: Needs Manager Approval

#2365 fix: handle optional adminKey flag safely in context configuration
  src/commands/node/configs.ts
Labels: PR: Needs Team Approval, PR: Needs Manager Approval
