Repository hiero-ledger/solo, pull requests merged in 2025-08, with the labels that each got.

#2397 fix: update post freeze CN source directory for application.properties
  src/commands/node/tasks.ts
Labels: PR: Needs Team Approval, PR: Needs Manager Approval

#2400 fix: remove unnecessary node logs from migration test workflow
  .github/workflows/flow-migration-test.yaml
Labels: PR: Ready to Merge

#2401 fix: do not assign mask value to default value for data sensitive flags
  src/commands/flags.ts
Labels: PR: Ready to Merge

#2417 feat: update command flags and ECDSA key documents
  docs/site/content/en/docs/faq.md
  src/commands/account.ts
  src/commands/block-node.ts
  src/commands/cluster/flags.ts
  src/commands/deployment.ts
  src/commands/explorer.ts
  src/commands/mirror-node.ts
  src/commands/network.ts
  src/commands/node/flags.ts
  src/commands/relay.ts
  test/e2e/commands/block-node.test.ts
Labels: PR: Needs Manager Approval

#2420 feat: updated smoke test help to debug intermittent failure
  .github/workflows/script/solo_smoke_test.sh
  examples/create-topic.js
  test/e2e/commands/tests/mirror-node-test.ts
Labels: PR: Needs Manager Approval

#2398 fix: address issues for solo node add/update/delete when using separate subcommands
  README.md
  Taskfile.tests.yml
  docs/site/Taskfile.mutate.yaml
  docs/site/Taskfile.yaml
  docs/site/content/en/examples/_index.md
  docs/site/content/en/templates/step-by-step-guide.template.md
  docs/site/hugo-template.yaml
  examples/node-create-transaction/README.md
  examples/node-create-transaction/Taskfile.yml
  examples/node-create-transaction/package-lock.json
  examples/node-create-transaction/package.json
  examples/node-create-transaction/solo-node-create-transaction.js
  examples/node-delete-transaction/README.md
  examples/node-delete-transaction/Taskfile.yml
  examples/node-delete-transaction/package-lock.json
  examples/node-delete-transaction/package.json
  examples/node-delete-transaction/solo-node-delete-transaction.js
  examples/node-update-transaction/README.md
  examples/node-update-transaction/Taskfile.yml
  examples/node-update-transaction/package-lock.json
  examples/node-update-transaction/package.json
  examples/node-update-transaction/solo-node-update-transaction.js
  resources/profiles/custom-spec.yaml
  src/business/runtime-state/api/remote-config-runtime-state-api.ts
  src/business/runtime-state/config/remote/remote-config-runtime-state.ts
  src/commands/explorer.ts
  src/commands/flags.ts
  src/commands/mirror-node.ts
  src/commands/node/config-interfaces/node-prepare-upgrade-config-class.ts
  src/commands/node/configs.ts
  src/commands/node/flags.ts
  src/commands/node/handlers.ts
  src/commands/node/index.ts
  src/commands/node/tasks.ts
  src/core/account-manager.ts
  src/core/constants.ts
  src/core/genesis-network-models/genesis-network-data-constructor.ts
  src/core/process-output.ts
  src/integration/kube/k8-client/resources/pod/k8-client-pod.ts
  src/integration/kube/k8-client/resources/pvc/k8-client-pvcs.ts
  src/integration/kube/k8-client/resources/secret/k8-client-secrets.ts
  test/unit/commands/cluster.test.ts
Labels: PR: Needs Team Approval, PR: Needs Manager Approval

#2424 feat(cli): implement solo quick start single destroy
  docs/site/content/en/docs/faq.md
  docs/site/content/en/templates/step-by-step-guide.template.md
  src/commands/cluster/handlers.ts
  src/commands/explorer.ts
  src/commands/mirror-node.ts
  src/commands/network.ts
  src/commands/quick-start/default-quick-start.ts
  src/commands/quick-start/quick-start-single-destroy-config-class.ts
  src/commands/relay.ts
  src/core/task-list/default-task-list.ts
  src/core/task-list/task-list.ts
  test/e2e/commands/quick-start-single.test.ts
  test/e2e/integration/core/dependency-managers/helm-dependency-manager.test.ts
  test/e2e/integration/core/kind/kind-client.test.ts
Labels: PR: Needs Team Approval

#2435 chore: increase build application workflow matrix max parallel from 3 to 5
  .github/workflows/flow-build-application.yaml
Labels: PR: Needs Team Approval, PR: Needs Manager Approval

#2446 chore: fixed a typo in the bash cleanup command by removing an unnecessary semicolon in two places in `step-by-step-guide.template.md`
  docs/site/content/en/templates/step-by-step-guide.template.md
  src/commands/cluster/tasks.ts
Labels: PR: Needs Team Approval, PR: Needs Manager Approval

#2452 fix: Migrate to using @hiero-ledger/sdk
  examples/create-topic.js
  examples/node-create-transaction/package-lock.json
  examples/node-create-transaction/package.json
  examples/node-create-transaction/solo-node-create-transaction.js
  examples/node-delete-transaction/package-lock.json
  examples/node-delete-transaction/package.json
  examples/node-delete-transaction/solo-node-delete-transaction.js
  examples/node-update-transaction/package-lock.json
  examples/node-update-transaction/package.json
  examples/node-update-transaction/solo-node-update-transaction.js
  examples/sdk-network-connection/package-lock.json
  examples/sdk-network-connection/package.json
  examples/sdk-network-connection/solo-network-connection.js
  package-lock.json
  package.json
  src/commands/account.ts
  src/commands/node/config-interfaces/node-add-config-class.ts
  src/commands/node/config-interfaces/node-add-context.ts
  src/commands/node/config-interfaces/node-delete-config-class.ts
  src/commands/node/config-interfaces/node-download-generated-files-config-class.ts
  src/commands/node/config-interfaces/node-prepare-upgrade-config-class.ts
  src/commands/node/config-interfaces/node-update-config-class.ts
  src/commands/node/config-interfaces/node-upgrade-config-class.ts
  src/commands/node/configs.ts
  src/commands/node/helper.ts
  src/commands/node/tasks.ts
  src/commands/quick-start/default-quick-start.ts
  src/commands/quick-start/predefined-accounts.ts
  src/core/account-manager.ts
  src/core/constants.ts
  src/core/genesis-network-models/genesis-network-data-constructor.ts
  src/core/genesis-network-models/genesis-network-node-data-wrapper.ts
  src/core/helpers.ts
  src/core/templates.ts
  src/types/index.ts
  test/e2e/commands/account.test.ts
  test/e2e/commands/node-delete.test.ts
  test/e2e/commands/node-local-hedera.test.ts
  test/e2e/commands/node-upgrade.test.ts
  test/e2e/commands/tests/node-test.ts
  test/test-utility.ts
Labels: PR: Ready to Merge

#2449 fix: update markdown documentation generation script
  .github/workflows/script/launch_network.sh
  .github/workflows/script/solo_smoke_test.sh
  .github/workflows/support/e2e-test-matrix.json
  .github/workflows/zxc-e2e-test.yaml
  Taskfile.tests.yml
  docs/site/content/en/templates/step-by-step-guide.template.md
  docs/site/update_md.sh
  src/argument-processor.ts
  src/commands/flags.ts
  test/e2e/commands/tests/mirror-node-test.ts
Labels: PR: Needs Team Approval, PR: Needs Manager Approval

#2422 feat: Add kubectl dependency manager
  .github/workflows/script/gcs_test.sh
  src/commands/init/init.ts
  src/core/constants.ts
  src/core/dependency-injection/container-init.ts
  src/core/dependency-injection/inject-tokens.ts
  src/core/dependency-managers/base-dependency-manager.ts
  src/core/dependency-managers/dependency-manager.ts
  src/core/dependency-managers/helm-dependency-manager.ts
  src/core/dependency-managers/index.ts
  src/core/dependency-managers/kind-dependency-manager.ts
  src/core/dependency-managers/kubectl-dependency-manager.ts
  src/core/templates.ts
  test/e2e/integration/core/dependency-managers/helm-dependency-manager.test.ts
  test/e2e/integration/core/dependency-managers/kind-dependency-manager.test.ts
  test/e2e/integration/core/dependency-managers/kubectl-dependency-manager.test.ts
  test/e2e/integration/core/kind/kind-client.test.ts
  version.ts
Labels: PR: Needs Team Approval

#2462 chore: Add E2E test validation for node address book update
  test/e2e/commands/node-update.test.ts
Labels: PR: Needs Team Approval, PR: Needs Manager Approval

#2463 fix: disable the setting of the gRPC web endpoint when running for apps that are not CN, bump MN to v0.136.0
  src/commands/node/tasks.ts
  version.ts
Labels: PR: Needs Team Approval, PR: Needs Manager Approval

#2472 feat: control block node version as environment variable
  docs/site/content/en/docs/env.md
  src/core/constants.ts
  version.ts
Labels: PR: Ready to Merge

#2505 fix: replace 2 second sleep with sync after remote copyFiles
  src/core/platform-installer.ts
Labels: Bug

#2527 docs: update ram requirements
  README.md
  docs/site/content/en/templates/step-by-step-guide.template.md
  images/docker-desktop.png
Labels: PR: Needs Team Approval
