Repository hiero-ledger/solo, pull requests merged in 2025-02, with the labels that each got.

#1288 refactor: created `kube/PodName` class and integrated into codebase
  .github/workflows/flow-task-test.yaml
  src/commands/mirror_node.ts
  src/commands/node/configs.ts
  src/commands/node/node_add_config.ts
  src/commands/node/tasks.ts
  src/core/account_manager.ts
  src/core/kube/k8.ts
  src/core/kube/k8_client.ts
  src/core/kube/kube_errors.ts
  src/core/kube/pod_name.ts
  src/core/kube/pods.ts
  src/core/kube/pvcs.ts
  src/core/network_node_services.ts
  src/core/platform_installer.ts
  src/core/templates.ts
  src/types/aliases.ts
  test/e2e/commands/mirror_node.test.ts
  test/e2e/commands/network.test.ts
  test/e2e/commands/node_delete.test.ts
  test/e2e/commands/node_update.test.ts
  test/e2e/commands/node_upgrade.test.ts
  test/e2e/commands/separate_node_delete.test.ts
  test/e2e/commands/separate_node_update.test.ts
  test/e2e/commands/separate_node_upgrade.test.ts
  test/e2e/e2e_node_util.ts
  test/e2e/integration/core/account_manager.test.ts
  test/e2e/integration/core/k8_e2e.test.ts
  test/e2e/integration/core/platform_installer_e2e.test.ts
  test/unit/core/platform_installer.test.ts
Labels: PR: Needs Approval

#1290 refactor: add k8.PodRef class and implement it across the codebase
  src/commands/mirror_node.ts
  src/commands/node/configs.ts
  src/commands/node/helper.ts
  src/commands/node/node_add_config.ts
  src/commands/node/tasks.ts
  src/core/account_manager.ts
  src/core/kube/k8.ts
  src/core/kube/k8_client.ts
  src/core/kube/kube_errors.ts
  src/core/kube/pod_ref.ts
  src/core/platform_installer.ts
  test/e2e/commands/mirror_node.test.ts
  test/e2e/commands/network.test.ts
  test/e2e/commands/node_delete.test.ts
  test/e2e/commands/node_update.test.ts
  test/e2e/commands/node_upgrade.test.ts
  test/e2e/commands/separate_node_add.test.ts
  test/e2e/commands/separate_node_delete.test.ts
  test/e2e/commands/separate_node_update.test.ts
  test/e2e/commands/separate_node_upgrade.test.ts
  test/e2e/e2e_node_util.ts
  test/e2e/integration/core/account_manager.test.ts
  test/e2e/integration/core/k8_e2e.test.ts
  test/e2e/integration/core/platform_installer_e2e.test.ts
  test/test_add.ts
  test/test_util.ts
  test/unit/core/platform_installer.test.ts
Labels: PR: Needs Approval

#1294 refactor: create k8.Container interface, move container methods from Pod to Container, implement K8ClientContainer and implement across codebase
  src/core/kube/container.ts
  src/core/kube/containers.ts
  src/core/kube/k8.ts
  src/core/kube/k8_client.ts
  src/core/kube/k8_client/k8_client_container.ts
  src/core/kube/k8_client/k8_client_containers.ts
  src/core/kube/pod.ts
Labels: PR: Needs Approval

#1231 feat: Separate concepts for namespace and deployment name
  .github/workflows/script/helper.sh
  .github/workflows/script/solo_smoke_test.sh
  .github/workflows/script/update_md.sh
  Taskfile.helper.yml
  Taskfile.yml
  docs/content/User/StepByStepGuide.md.template
  examples/Taskfile.examples.yml
  examples/custom-network-config/Taskfile.yml
  examples/performance-tuning/solo-gke/Taskfile.yml
  examples/performance-tuning/solo-perf-test/Taskfile.yml
  examples/solo-gke-test/Taskfile.yml
  src/commands/account.ts
  src/commands/cluster/flags.ts
  src/commands/cluster/handlers.ts
  src/commands/cluster/index.ts
  src/commands/cluster/tasks.ts
  src/commands/deployment.ts
  src/commands/explorer.ts
  src/commands/flags.ts
  src/commands/mirror_node.ts
  src/commands/network.ts
  src/commands/node/configs.ts
  src/commands/node/flags.ts
  src/commands/node/handlers.ts
  src/commands/node/node_add_config.ts
  src/commands/relay.ts
  src/core/config/local_config.ts
  src/core/config/local_config_data.ts
  src/core/config/remote/listr_config_tasks.ts
  src/core/config/remote/remote_config_manager.ts
  src/core/container_init.ts
  src/core/error_messages.ts
  src/core/resolvers.ts
  src/core/validator_decorators.ts
  src/index.ts
  test/data/local-config.yaml
  test/e2e/commands/mirror_node.test.ts
  test/e2e/commands/network.test.ts
  test/e2e/commands/relay.test.ts
  test/e2e/integration/core/account_manager.test.ts
  test/e2e/integration/core/remote_config_manager.test.ts
  test/setup.ts
  test/test_container.ts
  test/test_util.ts
  test/unit/commands/base.test.ts
  test/unit/commands/cluster.test.ts
  test/unit/commands/network.test.ts
  test/unit/core/certificate_manager.test.ts
  test/unit/core/dependency_managers/dependency_manager.test.ts
  test/unit/core/local_config.test.ts
  test/unit/core/profile_manager.test.ts
Labels: PR: Needs Approval

#1305 refactor: utilize k8.clusters methods
  src/commands/cluster/tasks.ts
  src/core/config/local_config.ts
  src/core/config/remote/remote_config_manager.ts
  src/core/kube/clusters.ts
  src/core/kube/k8.ts
  src/core/kube/k8_client.ts
  src/index.ts
  test/e2e/integration/core/k8_e2e.test.ts
  test/unit/commands/cluster.test.ts
Labels: PR: Ready to Merge

#1307 refactor: utilize k8.contexts methods
  src/commands/cluster/configs.ts
  src/commands/cluster/tasks.ts
  src/commands/deployment.ts
  src/core/config/local_config.ts
  src/core/config/remote/remote_config_manager.ts
  src/core/kube/contexts.ts
  src/core/kube/k8.ts
  src/core/kube/k8_client.ts
  src/index.ts
  test/e2e/integration/core/k8_e2e.test.ts
  test/unit/commands/cluster.test.ts
Labels: PR: Ready to Merge

#1306 refactor: utilize k8.ConfigMaps methods
  src/core/config/remote/remote_config_manager.ts
  src/core/kube/config_maps.ts
  src/core/kube/k8.ts
  src/core/kube/k8_client.ts
  test/unit/commands/network.test.ts
Labels: PR: Ready to Merge

#1308 refactor: add k8 ingress classes list implementation
  src/core/cluster_checks.ts
  src/core/kube/ingress_class.ts
  src/core/kube/ingress_classes.ts
  src/core/kube/k8.ts
  src/core/kube/k8_client.ts
  src/core/kube/k8_client/k8_client_ingress_class.ts
  src/core/kube/k8_client/k8_client_ingress_classes.ts
Labels: PR: Needs Approval

#1309 refactor: add k8 pods list for all namespaces implementation
  src/core/cluster_checks.ts
  src/core/kube/k8_client/k8_client_pod.ts
  src/core/kube/k8_client/k8_client_pods.ts
  src/core/kube/pod.ts
  src/core/kube/pods.ts
Labels: PR: Needs Approval

#1192 feat: create the v059x node-override.yaml via solo
  src/commands/node/handlers.ts
  src/commands/node/tasks.ts
  src/core/constants.ts
  src/core/genesis_network_models/genesis_network_data_constructor.ts
  src/core/node_overrides_model.ts
  src/core/platform_installer.ts
  src/core/templates.ts
  src/types/index.ts
Labels: PR: Needs Approval

#1196 chore: update ingress configuration for mirror explorer
  .github/workflows/script/solo_smoke_test.sh
  Taskfile.helper.yml
  docs/content/User/AccessHederaServices.md
  docs/content/User/SoloWithMirrorNode.md
  examples/performance-tuning/solo-gke/mirror-and-explorer-values.yaml
  examples/solo-gke-test/Taskfile.yml
  examples/solo-gke-test/ingress-values.yaml
  examples/solo-gke-test/mirror-node-values.yaml
  resources/hedera-explorer-values.yaml
  src/commands/deployment.ts
  src/commands/explorer.ts
  src/commands/flags.ts
  src/commands/mirror_node.ts
  src/core/account_manager.ts
  src/core/constants.ts
  src/core/kube/k8.ts
  src/core/kube/k8_client.ts
  test/e2e/commands/mirror_node.test.ts
  version.ts
Labels: PR: Ready to Merge

#1320 refactor: add k8.services().create()
  src/core/kube/k8_client/k8_client_services.ts
  src/core/kube/service_name.ts
  src/core/kube/service_ref.ts
  src/core/kube/services.ts
  test/e2e/integration/core/k8_e2e.test.ts
Labels: PR: Needs Approval

#1323 refactor: add k8 pvc create
  src/core/kube/k8.ts
  src/core/kube/k8_client.ts
  src/core/kube/k8_client/k8_client_config_maps.ts
  src/core/kube/k8_client/k8_client_pods.ts
  src/core/kube/k8_client/k8_client_pvcs.ts
  src/core/kube/k8_client/k8_client_secrets.ts
  src/core/kube/k8_client/k8_client_services.ts
  src/core/kube/k8_client/resources/pvc/k8_client_pvc.ts
  src/core/kube/k8_client/resources/pvc/k8_client_pvcs.ts
  src/core/kube/pvcs.ts
  src/core/kube/resources/pvc/pvc.ts
  src/core/kube/resources/pvc/pvc_name.ts
  src/core/kube/resources/pvc/pvc_ref.ts
  src/core/kube/resources/pvc/pvcs.ts
  test/e2e/integration/core/k8_e2e.test.ts
Labels: PR: Needs Approval

#1335 refactor: update codebase to use k8.containers methods directly & move patchConfigMap + patchIngress out of k8
  src/commands/explorer.ts
  src/commands/mirror_node.ts
  src/commands/node/tasks.ts
  src/core/kube/k8.ts
  src/core/kube/k8_client/k8_client.ts
  src/core/kube/k8_client/resources/config_map/k8_client_config_maps.ts
  src/core/kube/k8_client/resources/container/k8_client_container.ts
  src/core/kube/k8_client/resources/ingress/k8_client_ingresses.ts
  src/core/kube/resources/config_map/config_maps.ts
  src/core/kube/resources/container/container.ts
  src/core/kube/resources/ingress/ingresses.ts
  src/core/network_nodes.ts
  src/core/platform_installer.ts
  test/e2e/commands/node_delete.test.ts
  test/e2e/commands/node_update.test.ts
  test/e2e/commands/node_upgrade.test.ts
  test/e2e/commands/separate_node_delete.test.ts
  test/e2e/commands/separate_node_update.test.ts
  test/e2e/commands/separate_node_upgrade.test.ts
  test/e2e/integration/core/k8_e2e.test.ts
  test/e2e/integration/core/platform_installer_e2e.test.ts
  test/test_util.ts
Labels: PR: Needs Approval

#1230 feat(mirror-node): Enhance mirror-node external database feature
  .github/workflows/flow-task-test.yaml
  .github/workflows/script/helper.sh
  .github/workflows/script/solo_smoke_test.sh
  Taskfile.helper.yml
  examples/custom-mirror-node-database/scripts/init.sh
  examples/custom-mirror-node-database/values.yaml
  examples/external-database-test/Taskfile.yml
  examples/external-database-test/scripts/init.sh
  src/commands/flags.ts
  src/commands/mirror_node.ts
  src/commands/node/handlers.ts
  src/core/helpers.ts
  src/index.ts
  test/e2e/commands/mirror_node.test.ts
Labels: PR: Unresolved Comments

#1351 refactor: Update LocalConfig to support multiple clusters based on the new design
  src/commands/cluster/configs.ts
  src/commands/cluster/tasks.ts
  src/commands/deployment.ts
  src/core/config/local_config.ts
  src/core/config/local_config_data.ts
  src/core/config/remote/listr_config_tasks.ts
  src/core/config/remote/remote_config_manager.ts
  src/core/error_messages.ts
  src/core/validator_decorators.ts
  test/data/local-config.yaml
  test/e2e/integration/core/remote_config_manager.test.ts
  test/test_container.ts
  test/test_util.ts
  test/unit/commands/cluster.test.ts
  test/unit/commands/network.test.ts
  test/unit/core/local_config.test.ts
Labels: PR: Needs Approval

#1385 refactor: update solo node start to support multiple clusters
  src/commands/account.ts
  src/commands/mirror_node.ts
  src/commands/node/configs.ts
  src/commands/node/tasks.ts
  src/commands/relay.ts
  src/core/account_manager.ts
  src/core/helpers.ts
  src/core/model/consensus_node.ts
  src/core/model/solo_service.ts
  src/core/network_node_services.ts
  test/e2e/commands/account.test.ts
  test/e2e/commands/mirror_node.test.ts
  test/e2e/commands/node_local_hedera.test.ts
  test/e2e/commands/node_update.test.ts
  test/e2e/commands/separate_node_add.test.ts
  test/e2e/commands/separate_node_update.test.ts
  test/e2e/commands/separate_node_upgrade.test.ts
  test/test_add.ts
  test/test_util.ts
  test/unit/commands/base.test.ts
Labels: PR: Ready to Merge

#1384 feat(local-remote-config): added solo version to local config and remote config
  src/commands/cluster/tasks.ts
  src/commands/network.ts
  src/core/config/local_config.ts
  src/core/config/local_config_data.ts
  src/core/config/remote/cluster.ts
  src/core/config/remote/metadata.ts
  src/core/config/remote/remote_config_manager.ts
  src/core/config/remote/types.ts
  src/core/config_manager.ts
  src/core/error_messages.ts
  src/core/helpers.ts
  src/index.ts
  test/data/local-config.yaml
  test/test_util.ts
  test/unit/commands/base.test.ts
  test/unit/commands/cluster.test.ts
  test/unit/core/config/remote/cluster.test.ts
  test/unit/core/config/remote/metadata.test.ts
  test/unit/core/config/remote/remote_config_data_wrapper.test.ts
  test/unit/core/helpers.test.ts
  test/unit/core/local_config.test.ts
Labels: PR: Ready to Merge

#1394 feat(multi-cluster): 'solo relay deploy' to handle cluster-ref value
  src/commands/node/tasks.ts
  src/commands/relay.ts
  src/core/account_manager.ts
  src/core/helpers.ts
  src/core/platform_installer.ts
Labels: PR: Ready to Merge

#1377 chore: add cluster_ref to mirror and explorer command
  Taskfile.helper.yml
  src/commands/explorer.ts
  src/commands/mirror_node.ts
  src/commands/relay.ts
  test/e2e/commands/mirror_node.test.ts
Labels: PR: Checks Failed, PR: Unresolved Comments

#1373 chore: account init to update node admin key
  src/commands/account.ts
  src/commands/node/tasks.ts
  src/core/templates.ts
  test/e2e/commands/account.test.ts
  test/e2e/dual-cluster/README.md
Labels: PR: Ready to Merge

#1415 fix(network-command): wrong value passed to addDebugOptions inside the 'network' command
  src/commands/network.ts
Labels: PR: Needs Approval

#1407 feat(multi-cluster): make remote config validation compatible with multi-cluster K8 implementation
  src/core/config/remote/remote_config_manager.ts
  src/core/config/remote/remote_config_validator.ts
  test/e2e/integration/core/remote_config_validator.test.ts
Labels: PR: Needs Approval

#1399 feat(multi-cluster): updated 'solo account init' to upload secrets to all clusters
  src/commands/account.ts
  src/core/account_manager.ts
Labels: PR: Ready to Merge

#1401 fix(remote-config): get the namespace from the deployment inside the getNamespace() method
  eslint.config.mjs
  src/core/config/remote/remote_config_manager.ts
  src/core/resolvers.ts
  test/e2e/integration/core/remote_config_manager.test.ts
Labels: PR: Ready to Merge

#1439 fix: restart network pods after chart update
  src/commands/network.ts
Labels: PR: Ready to Merge

#1446 chore: Update document with deployment command
  docs/content/User/HederaDeveloper.md
  docs/content/User/PlatformDeveloper.md
  docs/content/User/SoloWithMirrorNode.md
  docs/content/User/StepByStepGuide.md.template
Labels: PR: Ready to Merge

#1434 fix: storage test script updated with new cluster ref flags
  .github/workflows/script/gcs_test.sh
Labels: PR: Ready to Merge

#1447 refactor: multiple cluster support for `solo network refresh`
  src/commands/network.ts
Labels: PR: Ready to Merge

#1424 feat(multi-cluster): Update 'relay destroy' and 'network destroy' to support multiple clusters
  src/commands/base.ts
  src/commands/mirror_node.ts
  src/commands/network.ts
  src/commands/relay.ts
  src/core/account_manager.ts
  src/core/config/remote/remote_config_manager.ts
Labels: PR: Ready to Merge

#1474 chore(middlewares): move the yargs middlewares inside their own class 'Middlewares'
  src/commands/deployment.ts
  src/core/middlewares.ts
  src/index.ts
Labels: PR: Needs Approval

#1456 chore: added placeholders for design doc and added recursive command subcommand help generation script
  .github/workflows/flow-hugo-publish.yaml
  .gitignore
  docs/Taskfile.yaml
  docs/config.toml
  docs/content/Developer/DesignDocs/ArchitectureAndSystemDesign.md
  docs/content/Developer/DesignDocs/CLIDesignAndInteraction.md
  docs/content/Developer/DesignDocs/CodebaseAndModuleDocumentation.md
  docs/content/Developer/DesignDocs/ErrorHandlingAndLogging.md
  docs/content/Developer/DesignDocs/InfrastructureAndDeployment.md
  docs/content/Developer/DesignDocs/ProjectOverviewAndHighLevelDocumentation.md
  docs/content/Developer/DesignDocs/SecurityAndPermissions.md
  docs/content/Developer/DesignDocs/TestingAndQualityAssurance.md
  docs/content/Developer/DesignDocs/_index.md
  docs/content/Developer/_index.md
  docs/content/User/DebugLog/HowToDebugHederaServicesAndPlatformSDK.md
  docs/content/User/GetStarted.md
  docs/content/User/SDK.md
  docs/content/User/SoloCLI.md
  docs/content/User/SoloCommands.md
  docs/content/User/StepByStepGuide.md
  docs/content/User/TaskTool.md
  docs/content/User/_index.md
  docs/content/_index.md
  docs/data/menu/main.yml
  docs/generate_help.sh
Labels: PR: Needs Approval

#1458 feat: node command for multi cluster support
  .github/workflows/zxc-e2e-test.yaml
  src/commands/base.ts
  src/commands/deployment.ts
  src/commands/network.ts
  src/commands/node/configs.ts
  src/commands/node/handlers.ts
  src/commands/node/tasks.ts
  src/commands/relay.ts
  src/core/account_manager.ts
  src/core/chart_manager.ts
  src/core/config/local_config.ts
  src/core/config/remote/remote_config_manager.ts
  src/core/model/consensus_node.ts
  test/e2e/commands/node_update.test.ts
  test/e2e/integration/commands/init.test.ts
  test/helpers/argv_wrapper.ts
  test/test_container.ts
  test/test_util.ts
Labels: PR: Needs Approval

#1484 chore(cli): replace usages of @listr2/prompt-adapter-enquirer with @listr2/prompt-adapter-inquirer
  package-lock.json
  package.json
  src/commands/cluster/configs.ts
  src/commands/cluster/tasks.ts
  src/commands/explorer.ts
  src/commands/flags.ts
  src/commands/mirror_node.ts
  src/commands/network.ts
  src/core/config/remote/common_flags_data_wrapper.ts
  src/core/resolvers.ts
Labels: PR: Ready to Merge

#1459 feat: node command for multi cluster support (part two)
  src/commands/node/handlers.ts
  src/commands/node/tasks.ts
  src/core/config/local_config.ts
  src/core/config/remote/remote_config_manager.ts
  src/core/network_nodes.ts
  test/e2e/commands/node_upgrade.test.ts
  test/e2e/commands/separate_node_upgrade.test.ts
Labels: PR: Ready to Merge

#1519 chore: fix warnings in AccountCommand
  src/commands/account.ts
  src/types/aliases.ts
Labels: PR: Ready to Merge

#1511 fix: reduce TPS value for pinger in mirror-node-values.yaml
  resources/mirror-node-values.yaml
Labels: PR: Needs Team Approval

#1507 chore: removed autogen tool
  .github/workflows/autogen/README.md
  .github/workflows/autogen/autogen.mjs
  .github/workflows/autogen/eslint.config.mjs
  .github/workflows/autogen/package-lock.json
  .github/workflows/autogen/package.json
  .github/workflows/autogen/src/index.mjs
  .github/workflows/templates/config.yaml
  .github/workflows/templates/template.flow-build-application.yaml
  .github/workflows/templates/template.flow-pull-request-checks.yaml
  .github/workflows/templates/template.zxc-code-analysis.yaml
  .github/workflows/templates/template.zxc-env-vars.yaml
  eslint.config.mjs
Labels: PR: Needs Team Approval

#1509 feat: add `-d` alias for `--deployment` flag in flags.ts
  Taskfile.yml
  examples/performance-tuning/solo-gke/Taskfile.yml
  examples/solo-gke-test/Taskfile.yml
  src/commands/flags.ts
  test/e2e/dual-cluster/setup-dual-e2e.sh
  test/e2e/setup-e2e.sh
Labels: PR: Needs Team Approval

#1550 chore: separate hugo generated site from other docs
  .github/workflows/flow-hugo-publish.yaml
  .github/workflows/script/update_md.sh
  .github/workflows/zxc-update-readme.yaml
  .gitignore
  docs/design/archive/.gitkeep
  docs/site/Taskfile.yaml
  docs/site/config.toml
  docs/site/content/Developer/DesignDocs/ArchitectureAndSystemDesign.md
  docs/site/content/Developer/DesignDocs/CLIDesignAndInteraction.md
  docs/site/content/Developer/DesignDocs/CodebaseAndModuleDocumentation.md
  docs/site/content/Developer/DesignDocs/ErrorHandlingAndLogging.md
  docs/site/content/Developer/DesignDocs/InfrastructureAndDeployment.md
  docs/site/content/Developer/DesignDocs/ProjectOverviewAndHighLevelDocumentation.md
  docs/site/content/Developer/DesignDocs/SecurityAndPermissions.md
  docs/site/content/Developer/DesignDocs/TestingAndQualityAssurance.md
  docs/site/content/Developer/DesignDocs/_index.md
  docs/site/content/Developer/_index.md
  docs/site/content/User/AccessHederaServices.md
  docs/site/content/User/DebugLog/HowToDebugHederaServicesAndPlatformSDK.md
  docs/site/content/User/DebugLog/HowToDebugHederaServicesAndPlatformSDK/hedera-breakpoint.png
  docs/site/content/User/DebugLog/HowToDebugHederaServicesAndPlatformSDK/jvm-hedera-app.png
  docs/site/content/User/DebugLog/HowToDebugHederaServicesAndPlatformSDK/jvm-platform-app.png
  docs/site/content/User/DebugLog/HowToDebugHederaServicesAndPlatformSDK/platform-breakpoint.png
  docs/site/content/User/DebugLog/HowToDebugHederaServicesAndPlatformSDK/select_network_node0.png
  docs/site/content/User/DebugLog/HowToDebugHederaServicesAndPlatformSDK/select_root_container.png
  docs/site/content/User/Env.md
  docs/site/content/User/FAQ.md
  docs/site/content/User/GetStarted.md
  docs/site/content/User/HederaDeveloper.md
  docs/site/content/User/PlatformDeveloper.md
  docs/site/content/User/SDK.md
  docs/site/content/User/SoloCLI.md
  docs/site/content/User/SoloCommands.md
  docs/site/content/User/SoloWithMirrorNode.md
  docs/site/content/User/StepByStepGuide.md
  docs/site/content/User/StepByStepGuide.md.template
  docs/site/content/User/TaskTool.md
  docs/site/content/User/_index.md
  docs/site/content/_index.md
  docs/site/data/menu/main.yml
  docs/site/data/menu/more.yml
  docs/site/generate_help.sh
  docs/site/jsdoc.conf.json
  docs/site/layouts/_default/_markup/render-link.html
Labels: P1

#1548 chore(security): update the 'ConfigManager.update()' logging to mask sensitive data
  src/core/config_manager.ts
  src/types/aliases.ts
Labels: PR: Ready to Merge

#1490 fix: increase resource of web3 pod
  resources/profiles/custom-spec.yaml
Labels: PR: Ready to Merge

#1553 chore: fix tsdoc warnings
  docs/site/Taskfile.yaml
  docs/site/content/User/SoloCommands.md
  src/commands/explorer.ts
  src/commands/mirror_node.ts
  src/commands/network.ts
  src/commands/node/configs.ts
  src/commands/node/tasks.ts
  src/core/account_manager.ts
  src/core/config/remote/enumerations.ts
  src/core/config/remote/remote_config_manager.ts
  src/core/constants.ts
  src/core/key_manager.ts
  src/core/kube/k8_client/k8_client_base.ts
  src/core/kube/k8_client/k8_client_factory.ts
  src/core/platform_installer.ts
  src/core/profile_manager.ts
Labels: PR: Needs Manager Approval

#1552 feat: split cloud storage credential for write and readonly access
  .github/workflows/script/gcs_test.sh
  resources/mirror-node-values.yaml
  resources/profiles/custom-spec.yaml
  src/commands/flags.ts
  src/commands/mirror_node.ts
  src/commands/network.ts
  test/e2e/commands/mirror_node.test.ts
  test/e2e/commands/network.test.ts
  test/test_util.ts
Labels: PR: Ready to Merge

#1562 feat: use subtask to create many account in parallel
  src/commands/account.ts
Labels: PR: Ready to Merge

#1398 fix: corrected cache dir flag not working and added dual cluster e2e test
  .github/workflows/flow-build-application.yaml
  .github/workflows/flow-pull-request-checks.yaml
  .github/workflows/script/update_md.sh
  .github/workflows/zxc-code-analysis.yaml
  .github/workflows/zxc-e2e-test.yaml
  .github/workflows/zxc-env-vars.yaml
  .github/workflows/zxc-update-readme.yaml
  Taskfile.helper.yml
  docs/site/content/User/StepByStepGuide.md
  package.json
  solo.ts
  src/commands/base.ts
  src/commands/flags.ts
  src/commands/mirror_node.ts
  src/commands/node/flags.ts
  src/commands/relay.ts
  src/core/config/remote/remote_config_manager.ts
  src/core/config_manager.ts
  src/core/constants.ts
  src/core/dependency_injection/container_init.ts
  src/core/kube/k8_client/resources/namespace/k8_client_namespaces.ts
  src/core/middlewares.ts
  src/core/profile_manager.ts
  src/core/resolvers.ts
  src/index.ts
  test/data/local-config.yaml
  test/e2e/commands/account.test.ts
  test/e2e/commands/dual_cluster_full.test.ts
  test/e2e/commands/relay.test.ts
  test/e2e/integration/core/platform_installer_e2e.test.ts
  test/e2e/integration/core/remote_config_validator.test.ts
  test/test_util.ts
  test/unit/commands/base.test.ts
  test/unit/core/config_manager.test.ts
  test/unit/core/local_config.test.ts
  test/unit/core/profile_manager.test.ts
Labels: PR: Needs Team Approval
