Repository hiero-ledger/solo, pull requests merged in 2025-06, with the labels that each got.

#2029 fix: block node start id, add new block id, update markdown for block commands
  .github/workflows/script/update_md.sh
  .github/workflows/script/wrapper_for_update_md.sh
  docs/site/content/en/docs/step-by-step-guide.md.template
  examples/Taskfile.examples.yml
  src/commands/block-node.ts
  src/core/config/remote/remote-config-validator.ts
  test/e2e/integration/core/remote-config-validator.test.ts
Labels: PR: Ready to Merge

#2067 feat: update migration test
  .github/workflows/flow-migration-test.yaml
  .github/workflows/script/launch_network.sh
  .github/workflows/script/solo_smoke_test.sh
  .github/workflows/support/v58-test/settings.txt
  src/business/runtime-state/config/local/local-config-runtime-state.ts
  src/business/utils/reflect-assist.ts
  src/commands/flags.ts
  src/commands/mirror-node.ts
  src/commands/network.ts
  src/commands/relay.ts
  src/core/chart-manager.ts
  test/unit/business/utils/path-ex.test.ts
  test/unit/business/utils/string-ex.test.ts
  test/unit/business/utils/version-range.test.ts
  test/unit/commands/network.test.ts
Labels: PR: Needs Team Approval, PR: Needs Manager Approval

#2126 chore: fix hugo build issue not picking up GH_TOKEN since it is in a Taskfile task call
  .github/workflows/flow-deploy-release-artifact.yaml
  .github/workflows/flow-hugo-publish.yaml
  .github/workflows/zxc-hugo-build.yaml
  .github/workflows/zxc-hugo-publish.yaml
  docs/site/Taskfile.github.yaml
  docs/site/Taskfile.yaml
Labels: PR: Needs Team Approval, PR: Needs Manager Approval

#2130 chore: update Hugo workflow names for clarity and improve dry run condition handling
  .github/workflows/flow-hugo-publish.yaml
  .github/workflows/zxc-hugo-publish.yaml
Labels: PR: Needs Team Approval, PR: Needs Manager Approval

#2145 fix: display title of failed task
  src/core/constants.ts
Labels: PR: Needs Team Approval

#2155 feat: update explorer to release 25.0.0
  version.ts
Labels: PR: Needs Manager Approval

#2153 fix: check upgrade package before perform upgrade
  src/commands/node/configs.ts
  src/core/constants.ts
Labels: PR: Ready to Merge

#2159 chore: update GCS storage test condition to exclude forked repositories
  .github/workflows/flow-gcs-test.yaml
Labels: PR: Needs Team Approval, PR: Needs Manager Approval

#2164 docs: restructured step-by-step guide to use layout provided by product manager, and updated to be leveraged by docs build
  .github/workflows/script/wrapper_for_update_md.sh
  .github/workflows/zxc-hugo-build.yaml
  .github/workflows/zxc-update-readme.yaml
  .gitignore
  README.md
  Taskfile.tests.yml
  docs/site/Taskfile.github.yaml
  docs/site/Taskfile.yaml
  docs/site/assets/scss/_variables_project.scss
  docs/site/content/en/docs/solo-commands.md
  docs/site/content/en/docs/solo-with-mirror-node.md
  docs/site/content/en/docs/step-by-step-guide.md
  docs/site/content/en/docs/step-by-step-guide.md.template
  docs/site/content/en/docs/step-by-step-guide.template.md
  docs/site/hugo-template.yaml
  docs/site/update_md.sh
  docs/site/wrapper_for_update_md.sh
  src/commands/relay.ts
Labels: PR: Needs Team Approval, PR: Needs Manager Approval

#2173 docs: update version table for release/0.37
  README.md
Labels: PR: Needs Team Approval

#2178 fix: incorrect logic
  src/commands/cluster/tasks.ts
Labels: PR: Ready to Merge

#2129 feat: able to manual run E2E test with different consensus version
  .github/workflows/flow-pull-request-checks.yaml
  .github/workflows/zxc-e2e-test.yaml
  Taskfile.tests.yml
  version.ts
Labels: PR: Ready to Merge

#2116 fix: Improvements to node upgrade e2e tests
  src/commands/node/handlers.ts
  src/commands/node/tasks.ts
  src/core/config-manager.ts
  src/core/helpers.ts
  src/core/network-nodes.ts
  src/core/profile-manager.ts
  test/e2e/commands/node-upgrade.test.ts
  test/test-utility.ts
Labels: PR: Needs Team Approval

#2220 chore: update condition for Hugo docs publish to include versioned release check
  .github/workflows/flow-hugo-publish.yaml
Labels: PR: Needs Team Approval, PR: Needs Manager Approval
