Repository hiero-ledger/solo, pull requests merged in 2025-04, with the labels that each got.

#1772 refactor: removed 'unicorn/no-array-for-each' rule violations
  eslint.config.mjs
  src/commands/base.ts
  src/commands/flags.ts
  src/commands/network.ts
  src/commands/node/tasks.ts
  src/commands/relay.ts
  src/core/account-manager.ts
  src/core/command-handler.ts
  src/core/config-manager.ts
  src/core/config/remote/components-data-wrapper.ts
  src/core/config/remote/components/relay-component.ts
  src/core/config/remote/remote-config-data-wrapper.ts
  src/core/config/remote/remote-config-manager.ts
  src/core/genesis-network-models/genesis-network-data-constructor.ts
  src/core/helpers.ts
  src/core/key-manager.ts
  src/core/logging/solo-winston-logger.ts
  src/core/network-nodes.ts
  src/core/node-overrides-model.ts
  src/core/platform-installer.ts
  src/core/process-output.ts
  src/core/shell-runner.ts
  src/core/templates.ts
  src/core/zippy.ts
  src/integration/helm/execution/helm-execution-builder.ts
  src/integration/helm/execution/helm-execution.ts
  src/integration/kube/k8-client/resources/ingress-class/k8-client-ingress-classes.ts
  src/integration/kube/k8-client/resources/ingress/k8-client-ingresses.ts
  src/integration/kube/k8-client/resources/namespace/k8-client-namespaces.ts
  src/integration/kube/k8-client/resources/pod/k8-client-pods.ts
  test/e2e/integration/core/helm/helm-client.test.ts
  test/unit/commands/base.test.ts
  test/unit/core/config/remote/components-data-wrapper.test.ts
  test/unit/core/profile-manager.test.ts
  test/unit/core/templates.test.ts
  test/unit/data/key/lexer/forest.test.ts
Labels: PR: Needs Team Approval, PR: Needs Manager Approval

#1773 refactor: removed 'unicorn/switch-case-braces' and 'unicorn/numeric-separators-style' rule violations
  eslint.config.mjs
  src/commands/explorer.ts
  src/commands/flags.ts
  src/commands/network.ts
  src/commands/node/handlers.ts
  src/commands/node/tasks.ts
  src/core/account-manager.ts
  src/core/config-manager.ts
  src/core/config/remote/components-data-wrapper.ts
  src/core/constants.ts
  src/core/templates.ts
  src/data/backend/impl/environment-storage-backend.ts
  src/data/backend/impl/file-storage-backend.ts
  src/data/configuration/impl/layered-config.ts
  src/data/mapper/impl/flat-key-mapper.ts
  src/data/schema/model/utils/transformations.ts
  test/e2e/commands/account.test.ts
  test/e2e/commands/dual-cluster-full.test.ts
  test/e2e/commands/mirror-node.test.ts
  test/e2e/integration/core/helm/helm-client.test.ts
  test/unit/data/schema/model/remote/remote-config.test.ts
Labels: PR: Needs Team Approval, PR: Needs Manager Approval

#1765 fix: unzip running on M3 chip
  resources/extract-platform.sh
  resources/support-zip.sh
  src/core/helpers.ts
  src/core/network-nodes.ts
  src/core/platform-installer.ts
Labels: PR: Ready to Merge

#1778 refactor: removed rule violations for unicorn rules: `prefer-number-properties`, `no-negated-condition`, `explicit-length-check`
  eslint.config.mjs
  src/business/utils/version.ts
  src/commands/account.ts
  src/commands/cluster/tasks.ts
  src/commands/deployment.ts
  src/commands/flags.ts
  src/commands/mirror-node.ts
  src/commands/network.ts
  src/commands/node/helper.ts
  src/commands/node/tasks.ts
  src/core/account-manager.ts
  src/core/certificate-manager.ts
  src/core/chart-manager.ts
  src/core/config-manager.ts
  src/core/config/local/local-config-data-wrapper.ts
  src/core/config/remote/remote-config-validator.ts
  src/core/helpers.ts
  src/core/lock/interval-lock.ts
  src/core/network-nodes.ts
  src/core/node-overrides-model.ts
  src/core/platform-installer.ts
  src/core/profile-manager.ts
  src/core/resolvers.ts
  src/core/templates.ts
  src/core/validator-decorators.ts
  src/data/key/lexer/lexer.ts
  src/data/key/prefix.ts
  src/integration/helm/base/api/version/semantic-version.ts
  src/integration/helm/execution/helm-execution.ts
  src/integration/kube/k8-client/resources/cluster/k8-client-clusters.ts
  src/integration/kube/k8-client/resources/config-map/k8-client-config-maps.ts
  src/integration/kube/k8-client/resources/ingress/k8-client-ingresses.ts
  src/integration/kube/k8-client/resources/namespace/k8-client-namespaces.ts
  src/integration/kube/k8-client/resources/pod/k8-client-pod.ts
Labels: PR: Needs Team Approval, PR: Needs Manager Approval

#1776 chore: added mirror-node and explorer to `dual-cluster-full.test.ts`, deleted `mirror-node.test.ts`, bump solo-charts to v0.49.1
  .github/workflows/flow-build-application.yaml
  .github/workflows/flow-pull-request-checks.yaml
  .github/workflows/zxc-code-analysis.yaml
  .github/workflows/zxc-env-vars.yaml
  package.json
  test/e2e/commands/dual-cluster-full.test.ts
  test/e2e/commands/mirror-node.test.ts
  version.ts
Labels: PR: Needs Team Approval, PR: Needs Manager Approval

#1777 docs: add initial version of presentation layer cli design documentation
  docs/design/architecture/system/presentation_layer_architecture.md
  docs/design/architecture/system/presentation_layer_cli_architecture.md
  src/commands/network.ts
Labels: P0

#1485 chore: move test scripts from 'package.json' to 'Taskfile'
  .github/workflows/flow-build-application.yaml
  .github/workflows/flow-deploy-release-artifact.yaml
  .github/workflows/flow-gcs-test.yaml
  .github/workflows/flow-pull-request-checks.yaml
  .github/workflows/flow-task-test.yaml
  .github/workflows/zxc-code-style.yaml
  .github/workflows/zxc-e2e-test.yaml
  .github/workflows/zxc-unit-test.yaml
  .github/workflows/zxc-update-readme.yaml
  DEV.md
  Taskfile.helper.yml
  Taskfile.tests.yml
  Taskfile.yml
  docs/site/Taskfile.yaml
  examples/Taskfile.examples.yml
  examples/custom-network-config/Taskfile.yml
  examples/external-database-test/Taskfile.yml
  examples/network-with-domain-names/Taskfile.yaml
  examples/performance-tuning/latitude/Taskfile.yml
  package.json
  solo-compose/setup-runner.sh
  test/e2e/dual-cluster/setup-dual-e2e.sh
Labels: PR: Needs Team Approval, PR: Needs Manager Approval

#1785 chore: update markdown generation
  .github/workflows/script/update_md.sh
  .github/workflows/zxc-update-readme.yaml
  docs/site/content/User/StepByStepGuide.md
  docs/site/content/User/StepByStepGuide.md.template
Labels: PR: Needs Team Approval

#1787 fix: task with mirror
  docs/site/content/User/SDK.md
  docs/site/content/User/TaskTool.md
  examples/Taskfile.examples.yml
  examples/Taskfile.yml
Labels: PR: Needs Manager Approval

#1793 refactor: eslint --fix
  src/commands/cluster/tasks.ts
  src/commands/node/tasks.ts
  src/core/account-manager.ts
  src/core/config-manager.ts
  src/core/config/local/local-config-data-wrapper.ts
  src/core/dependency-managers/dependency-manager.ts
  src/core/dependency-managers/helm-dependency-manager.ts
  src/core/help-renderer.ts
  src/core/helpers.ts
  src/core/lock/interval-lock-renewal.ts
  src/core/lock/interval-lock.ts
  src/core/profile-manager.ts
  src/data/configuration/impl/layered-config-source.ts
  src/data/key/lexer/forest.ts
  src/data/key/lexer/lexer-internal-node.ts
  src/data/key/lexer/lexer.ts
  src/integration/helm/execution/helm-execution-builder.ts
  src/integration/helm/execution/helm-execution.ts
  src/integration/helm/model/version.ts
  src/integration/kube/k8-client/resources/config-map/k8-client-config-maps.ts
  src/integration/kube/k8-client/resources/container/k8-client-container.ts
  src/integration/kube/k8-client/resources/secret/k8-client-secrets.ts
  test/e2e/integration/core/helm/helm-client.test.ts
  test/test-add.ts
  test/unit/core/helm/software/helm-software-loader.test.ts
  test/unit/data/backend/impl/file-storage-backend.test.ts
  test/unit/fixtures/simple-object-storage-backend.fixture.ts
  version.ts
Labels: PR: Needs Team Approval, PR: Needs Manager Approval

#1797 docs: update GetStarted.md and README.md for improved user guidance
  README.md
  docs/site/content/User/GetStarted.md
Labels: PR: Needs Team Approval, PR: Needs Manager Approval

#1798 chore: add default-with-mirror in gcs test workflow
  .github/workflows/script/gcs_test.sh
  .github/workflows/script/helper.sh
  .github/workflows/script/solo_smoke_test.sh
Labels: PR: Ready to Merge

#1801 fix: updated GitHub Pages docs, fixed `solo deployment create` to prompt for additional flags
  .github/workflows/flow-hugo-publish.yaml
  .github/workflows/script/update_md.sh
  .gitignore
  README.md
  docs/content/Developer/Development/TaskTool.md
  docs/content/User/AccessHederaServices.md
  docs/content/User/DebugLog/index.md
  docs/content/User/FAQ.md
  docs/content/User/GetStarted.md
  docs/content/User/HederaDeveloper.md
  docs/content/User/PlatformDeveloper.md
  docs/content/User/SDK.md
  docs/content/User/SoloCLI.md
  docs/content/User/SoloWithMirrorNode.md
  docs/content/User/StepByStepGuide.md
  docs/content/User/StepByStepGuide.md.template
  docs/data/menu/main.yml
  src/commands/deployment.ts
Labels: PR: Needs Team Approval, PR: Needs Manager Approval

#1836 fix: Update flow-pull-request-formatting.yaml
  .github/workflows/flow-pull-request-formatting.yaml
Labels: dependencies

#1829 chore(typescript): enable typescript's "noImplicitOverride" and fix all errors
  src/core/config/remote/components/consensus-node-component.ts
  src/core/config/remote/components/relay-component.ts
  src/core/errors/solo-error.ts
  src/core/genesis-network-models/genesis-network-node-data-wrapper.ts
  src/core/genesis-network-models/genesis-network-roster-entry-data-wrapper.ts
  src/core/model/solo-service.ts
  src/core/process-output.ts
  src/data/key/config-key-error.ts
  src/data/schema/model/utils/transformation-error.ts
  src/integration/helm/base/api/version/invalid-semantic-version-exception.ts
  src/integration/helm/helm-configuration-exception.ts
  src/integration/helm/helm-execution-exception.ts
  tsconfig.json
Labels: PR: Needs Team Approval, PR: Needs Manager Approval

#1854 fix: change service endpoints from byte array to base64 string for creating genesis network json file
  src/core/genesis-network-models/genesis-network-data-wrapper.ts
  src/core/genesis-network-models/genesis-network-node-data-wrapper.ts
  src/core/helpers.ts
  src/types/index.ts
  test/e2e/commands/dual-cluster-full.test.ts
  test/unit/core/helpers.test.ts
  version.ts
Labels: PR: Needs Team Approval, PR: Needs Manager Approval

#1859 fix: include symbolic link file in downloading node logs
  resources/support-zip.sh
Labels: PR: Ready to Merge

#1853 docs(cli): complete missing operation descriptions and merge duplicate sections
  docs/design/architecture/system/presentation_layer_cli_architecture.md
Labels: PR: Unresolved Comments

#1885 chore: always delete cloud storage bucket
  .github/workflows/flow-gcs-test.yaml
Labels: PR: Ready to Merge

#1897 chore: Step by step guide updates
  docs/site/content/User/FAQ.md
  docs/site/content/User/SoloCommands.md
  docs/site/content/User/StepByStepGuide.md
  docs/site/content/User/StepByStepGuide.md.template
Labels: PR: Needs Team Approval, PR: Needs Manager Approval
